Object.assign(paths,{mic:'<rect x="8" y="2" width="8" height="13" rx="4"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3m-4 0h8"/>',back:'<path d="m15 5-7 7 7 7"/>',plus:'<path d="M12 5v14M5 12h14"/>',check:'<path d="m5 12 4 4L19 6"/>',pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',star:'<path d="m12 2 3 6 7 1-5 5 1 8-6-4-6 4 1-8-5-5 7-1Z"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',filter:'<path d="M3 4h18l-7 8v7l-4 2v-9Z"/>',edit:'<path d="m14 5 5 5M4 20l1-6L16 3l5 5L10 19Z"/>',compare:'<path d="M5 3v18m14-18v18M2 7h6m8 10h6M9 7h5m-3-3 3 3-3 3M15 17h-5m3-3-3 3 3 3"/>'});
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const I=(name)=>`<span data-icon="${name}"><svg viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.file}</svg></span>`;
function icons(){document.querySelectorAll('[data-icon]').forEach(el=>{if(!el.firstChild)el.innerHTML=I(el.dataset.icon).replace(/^<span[^>]*>|<\/span>$/g,'')})}icons();
const scroll=$('#scroll'),header=$('header'),nav=$('nav'),sheet=$('#sheet'),homeHTML=scroll.innerHTML,homeHeader=header.innerHTML;
const PET_KEY='pawcare-pets-v1';
let petStore;try{petStore=JSON.parse(localStorage.getItem(PET_KEY));}catch{}
if(!petStore?.pets?.length)petStore={active:'doudou',pets:[{id:'doudou',name:'豆豆',species:'猫',breed:'布偶猫',years:3,months:2,sex:'公',neutered:'已绝育',weight:5.2,notes:'喜欢安静的环境，就诊时请轻声安抚。',photo:'cat'},{id:'kele',name:'可乐',species:'狗',breed:'边境牧羊犬',years:2,months:0,sex:'公',neutered:'未绝育',weight:18.5,notes:'精力充沛，外出就诊时记得带牵引绳。',photo:'dog'}],data:{}};
// Reset the old sample once; subsequent visit-generated plans remain saved.
if(!petStore.sampleAMovedToVisit){
 for(const data of Object.values(petStore.data||{}))if(data.meds)data.meds=data.meds.filter(m=>!/^处方口服药\s*A(?:（演示）)?$/.test(m.name));
 petStore.sampleAMovedToVisit=true;
 localStorage.setItem(PET_KEY,JSON.stringify(petStore));
}
function currentPet(){return petStore.pets.find(p=>p.id===petStore.active)||petStore.pets[0];}
const petAge=p=>`${p.years}岁${+p.months?p.months+'个月':''}`;
const petFields=['careMode','carePurpose','symptoms','duration','appetite','energy','compare','archived','review','reviewTime','remind','booked','extraRecords','meds'];
function savePets(){try{petStore.data[petStore.active]=Object.fromEntries(petFields.map(k=>[k,state[k]]));localStorage.setItem(PET_KEY,JSON.stringify(petStore));}catch{}}
function switchPet(id){if(!petStore.pets.some(p=>p.id===id))return;savePets();petStore.active=id;Object.assign(state,petStore.data[id]||{symptoms:[],duration:'',appetite:'',energy:'',compare:[],archived:false,review:'',reviewTime:'10:00',remind:false,booked:false,extraRecords:[],meds:[]});state.archiveTab='时间轴';state.medTab='当前用药';render();}
const state={route:'home',history:[],symptoms:[],duration:'',appetite:'',energy:'',filter:'综合推荐',specialty:'全部',compare:[],archiveTab:'时间轴',medTab:'当前用药',archived:false,review:'2025-08-21',reviewTime:'10:00',remind:false,booked:false,extraRecords:[],meds:[{id:2,name:'处方口服液 B',method:'口服',dose:'2 ml',frequency:'每日 2 次',days:14,day:5,taken:false,remind:false}]};
const hospitals=[{id:1,name:'瑞鹏宠物医院',branch:'万象城分院',distance:1.2,rating:4.9,area:'徐汇区',tags:['皮肤专科强','猫科特色','设备先进'],hours:'08:00–22:00',price:'¥200–500',feature:'过敏检测设备齐全',x:.055,y:.262,w:.266,h:.128},{id:2,name:'宠颐生动物医院',branch:'静安分院',distance:3.5,rating:4.8,area:'静安区',tags:['内科综合','猫科特色','24小时接诊'],hours:'24小时接诊',price:'¥180–450',feature:'猫科友好 · 独立诊室',x:.055,y:.413,w:.266,h:.127},{id:3,name:'上海申普宠物医院',branch:'浦东分院',distance:5.8,rating:4.7,area:'浦东新区',tags:['内科综合','体检中心','环境舒适'],hours:'08:00–22:00',price:'¥180–500',feature:'多学科联合接诊',x:.055,y:.575,w:.266,h:.126},{id:4,name:'顽皮家宠物医院',branch:'长宁分院',distance:6.1,rating:4.9,area:'长宁区',tags:['猫科特色','体检中心','环境舒适'],hours:'08:30–21:00',price:'¥200–550',feature:'猫咪独立候诊区',x:.055,y:.728,w:.266,h:.126}];
const crop=(page,x,y,w,h,cls='',alt='')=>`<div class="source-photo ${cls}" role="img" aria-label="${esc(alt)}"><img alt="" src="assets/reference-${page}.png" style="width:${100/w}%;height:${100/h}%;left:${-100*x/w}%;top:${-100*y/h}%"></div>`;
const hospitalPhoto=(h,cls='')=>h.id===1?crop(4,.047,.093,.31,.138,cls,h.name+'医院实景'):crop(2,h.x,h.y,h.w,h.h,cls,h.name+'医院实景');
const avatar=(p=currentPet())=>`<div class="avatar ${p.photo==='dog'?'dog-avatar':p.photo==='cat'?'cat-avatar':'plain-avatar'}" role="img" aria-label="${esc(p.breed+' '+p.name)}">${p.photo==='none'?I('paw'):''}</div>`;
const petMini=()=>`<div class="pet-mini">${avatar()}<div><b>${esc(currentPet().name)}</b><span>${esc(currentPet().breed)} · ${petAge(currentPet())}</span></div><small>${currentPet().weight} kg</small></div>`;
const tags=list=>`<div class="tag-list">${list.map(s=>`<span>${esc(s)}</span>`).join('')}</div>`;
const summary=()=>`<dl class="summary-list"><div><dt>主要症状</dt><dd>${state.symptoms.length?state.symptoms.map(esc).join('、'):'等待选择'}</dd></div><div><dt>持续时间</dt><dd>${state.duration||'等待选择'}</dd></div><div><dt>状态变化</dt><dd>${[state.appetite&&'食欲'+state.appetite,state.energy&&'精神'+state.energy].filter(Boolean).join('，')||'等待补充'}</dd></div></dl>`;
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function modal(name,html){$('#sheet-title').textContent=name;$('#sheet-body').innerHTML=html;if(!sheet.open)sheet.showModal();}
function footer(html){let f=$('#route-footer');if(!f){f=document.createElement('div');f.id='route-footer';$('.phone').insertBefore(f,nav);}f.innerHTML=html;}
function go(route,back=false){$('#toast').classList.remove('show');if(sheet.open)sheet.close();if(!back&&route!==state.route)state.history.push(state.route);state.route=route;render();scroll.scrollTop=0;}
function renderOriginal(){const r=state.route;$('.phone').classList.toggle('inner-page',r!=='home');header.innerHTML=r==='home'?homeHeader:`<div class="page-head"><button data-action="back" aria-label="返回">${I('back')}</button><h1>${({symptom:'记录症状',hospitals:'推荐医院',compare:'医院对比',visit:'就诊记录详情',archive:'豆豆的医疗档案',medication:'用药管理',profile:'我的',petdetail:'宠物档案'})[r]}</h1><span class="head-step">${r==='symptom'?'1 / 3':r==='hospitals'?'2 / 3':r==='compare'?'3 / 3':''}</span></div>`;
const isMain=['home','archive','medication','profile'].includes(r);nav.style.display=isMain?'flex':'none';$('#route-footer')?.remove();scroll.classList.toggle('page-scroll',r!=='home');
nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.nav===({home:'home',archive:'archive',medication:'medicine',profile:'pet'})[r]));
if(r==='home'){scroll.innerHTML=homeHTML;const done=state.meds[0]?.taken;$('#med-btn').textContent=done?'已完成':'去完成';$('#meddesc').textContent=done?'今日用药已记录':'按处方用药 · 随餐服用';scroll.querySelector('.visit-info p').innerHTML=I('calendar')+'2025.08.14 <span class="tag">猫科</span>';scroll.querySelector('.metrics button:last-child b').textContent=state.review.slice(5).replace('-','月')+'日';scroll.querySelector('.reminder:last-child p').textContent=state.review.slice(5).replace('-','月')+'日 · 瑞鹏宠物医院';}
if(r==='symptom')renderSymptom();if(r==='hospitals')renderHospitals();if(r==='compare')renderCompare();if(r==='visit')renderVisit();if(r==='archive')renderArchive();if(r==='medication')renderMedication();if(r==='profile')renderProfile();if(r==='petdetail')renderPetDetail();icons();}
function choices(label,key,options,multi=false){return `<fieldset><legend>${label}${multi?'<small>可多选</small>':''}</legend><div class="choice-grid ${options.length===6?'six':''}">${options.map(v=>`<button aria-pressed="${multi?state[key].includes(v):state[key]===v}" class="choice ${(multi?state[key].includes(v):state[key]===v)?'selected':''}" data-choice="${key}" data-value="${v}">${v}</button>`).join('')}</div></fieldset>`}
function renderSymptom(){scroll.innerHTML=`${petMini()}<button class="voice-entry" data-action="voice">${I('mic')}<div><b>语音描述</b><small>说出观察到的变化，帮你整理</small></div>${I('chevron')}</button><div class="form-surface">${choices('常见症状','symptoms',['呕吐','腹泻','食欲下降','咳嗽','抓挠瘙痒','其他'],true)}${choices('持续时间','duration',['＜1天','1–3天','＞3天'])}${choices('食欲','appetite',['正常','下降','几乎不吃'])}${choices('精神状态','energy',['正常','稍差','明显变差'])}</div><section class="summary-card"><h2>${I('clipboard')}初步整理结果</h2>${summary()}<p class="microcopy">仅整理就医信息，不是疾病诊断。</p></section>`;footer(`<button class="cta" data-action="next-hospital">下一步：选择医院 ${I('arrow')}</button>`)}
function filteredHospitals(){let list=hospitals.filter(h=>state.specialty==='全部'||h.tags.some(t=>t.includes(state.specialty)));if(state.filter==='距离最近')list.sort((a,b)=>a.distance-b.distance);if(state.filter==='评分最高')list.sort((a,b)=>b.rating-a.rating||a.distance-b.distance);return list;}
function renderHospitals(){scroll.innerHTML=`<div class="need-note">${I('stethoscope')}<div>基于豆豆的就医需求<small>${state.symptoms.length?state.symptoms.map(esc).join(' · '):'请选择适合的医院'}${state.duration?' · '+state.duration:''}</small></div></div><div class="filter-bar">${['综合推荐','距离最近','评分最高','专科筛选'].map(t=>`<button class="${(state.filter===t||(t==='专科筛选'&&state.specialty!=='全部'))?'selected':''}" data-filter="${t}" ${t==='专科筛选'?'aria-expanded="false" aria-controls="specialty-dropdown"':''}>${t==='专科筛选'?I('filter'):''}${t}</button>`).join('')}</div>${state.specialty!=='全部'?`<p class="filter-result">当前专科：${state.specialty} <button data-action="clear-filter">清除</button></p>`:''}<div class="hospital-list">${filteredHospitals().map(h=>`<article class="hospital-card"><div class="hospital-main">${hospitalPhoto(h)}<div><h2>${h.name}</h2><p class="branch">${h.branch}</p><div class="hospital-facts"><span class="rating">★ ${h.rating.toFixed(1)}</span><span>${h.distance} km · ${h.area}</span></div></div></div>${tags(h.tags)}<div class="hospital-bottom"><span>${I('clock')}${h.hours}</span><button class="compare-toggle ${state.compare.includes(h.id)?'checked':''}" data-compare="${h.id}" aria-pressed="${state.compare.includes(h.id)}">${I(state.compare.includes(h.id)?'check':'plus')}${state.compare.includes(h.id)?'已加入':'加入对比'}</button></div></article>`).join('')}</div><p class="microcopy centered">评分、距离与费用为演示数据</p>`;renderCompareFooter();}
function renderCompareFooter(){footer(`<div class="compare-footer"><div><b>已选择 ${state.compare.length} 家医院</b><div class="mini-photos">${state.compare.map(id=>hospitalPhoto(hospitals.find(h=>h.id===id),'tiny')).join('')}${state.compare.length<2?'<span class="empty-photo">＋</span>':''}</div></div><button class="cta" data-action="compare" ${state.compare.length!==2?'disabled':''}>对比医院${state.compare.length?'（'+state.compare.length+'）':''}</button></div>`)}
function renderCompare(){if(state.compare.length!==2){go('hospitals',true);return;}const [a,b]=state.compare.map(id=>hospitals.find(h=>h.id===id));const skin=state.symptoms.includes('抓挠瘙痒');const preferred=skin?([a,b].find(h=>h.tags.includes('皮肤专科强'))||a):([a,b].find(h=>h.tags.includes('内科综合'))||a);state.recommended=preferred.id;const dims=[['距离',a.distance+' km',b.distance+' km','pin'],['评分',a.rating.toFixed(1)+' / 5',b.rating.toFixed(1)+' / 5','star'],['专科优势',a.tags.slice(0,2).join(' · '),b.tags.slice(0,2).join(' · '),'stethoscope'],['接诊时间',a.hours,b.hours,'clock'],['参考费用',a.price,b.price,'record'],['医院特色',a.feature,b.feature,'heart']];scroll.innerHTML=`<div class="comparison-head">${[a,b].map(h=>`<div>${hospitalPhoto(h)}<h2>${h.name}</h2><p>${h.branch}</p><strong>★ ${h.rating} <span>· ${h.distance} km</span></strong>${tags([h.tags[0]])}</div>`).join('')}</div><div class="dimensions">${dims.map(([label,av,bv,ic],i)=>`<section class="dimension"><h3>${I(ic)}${label}</h3><div class="dimension-values"><div>${av}${i<2?`<span class="meter"><i style="width:${i===0?100-a.distance*10:a.rating/5*100}%"></i></span>`:''}</div><div>${bv}${i<2?`<span class="meter"><i style="width:${i===0?100-b.distance*10:b.rating/5*100}%"></i></span>`:''}</div></div></section>`).join('')}</div><section class="recommendation"><h2>${I('check')}综合选择建议</h2><p>${preferred.name}${skin?'的皮肤专科更贴近豆豆当前的抓挠问题':'的'+(preferred.tags.includes('内科综合')?'内科服务':'猫科特色')+'更贴近本次就医需求'}${preferred.distance<=Math.min(a.distance,b.distance)?'，距离也更近':'，可结合距离和接诊时间选择'}。</p></section><p class="microcopy centered">演示建议仅用于比较服务信息，不代表医疗诊断。费用以医院确认为准。</p>`;footer(`<div class="dual-actions"><button class="outline-btn" data-route="hospitals">继续对比</button><button class="cta" data-action="book">预约这家医院</button></div>`)}
const medicalCards=[['就诊原因','食欲下降、偶有呕吐、精神状态一般','record','就诊前两天食欲下降，偶有呕吐，精神状态一般。以上为演示病历中的就诊描述。'],['诊断结果','急性胃肠炎','stethoscope','示例病历诊断：急性胃肠炎。本内容用于展示就诊记录结构，不是对真实宠物的诊断。'],['治疗方案','口服药物 + 肠胃护理 + 调整饮食','pill','示例记录采用口服药物、肠胃护理与饮食调整。具体药物、剂量和疗程需以真实处方为准。'],['医生建议','观察饮食和精神状态，如反复及时复诊','clipboard','示例医嘱：记录饮食和精神状态变化，按约复诊；如症状反复，及时联系宠物医生。']];
function reports(){return `<div class="report-grid">${['血常规','腹部超声','生化检查'].map((n,i)=>`<button data-report="${i}">${crop(4,.052+i*.24,.689,.218,.065,'report-photo',n+'示例缩略图')}<b>${n}</b><small>2025.08.14</small></button>`).join('')}</div>`}
function renderVisit(){scroll.innerHTML=`<section class="visit-header">${hospitalPhoto(hospitals[0])}<div><h2>瑞鹏宠物医院</h2><p>万象城分院</p><span>2025.08.14 · 10:30</span><p>李医生 · 猫科</p></div></section>${petMini()}<div class="medical-cards">${medicalCards.map(([name,desc,ic],i)=>`<button data-medical="${i}"><span class="soft-icon">${I(ic)}</span><div><h2>${name}</h2><p>${desc}</p></div>${I('chevron')}</button>`).join('')}</div><section class="section-block"><div class="section-heading"><h2>检查报告</h2><span>共 3 项</span></div>${reports()}</section><p class="microcopy centered">病历、医生与处方均为原型演示内容。</p>`;footer(`<div class="visit-footer"><button class="outline-btn" data-action="save-archive">${I(state.archived?'check':'plus')}${state.archived?'已加入档案':'加入医疗档案'}</button><button class="outline-btn" data-action="review">${I('calendar')}设置复诊提醒</button><button class="cta" data-action="make-plan">生成用药计划</button></div>`)}
const baseRecords=[{date:'2025.08.14',type:'就诊',name:'皮肤炎（疑似过敏）',hospital:'瑞鹏宠物医院',doctor:'李医生 · 皮肤科',tags:['皮肤问题','过敏','用药治疗'],result:'症状已有明显好转。',detail:'本条为示例皮肤科记录，与胃肠炎就诊记录分开保存。'}, {date:'2025.05.20',type:'体检',name:'年度体检',hospital:'美联众合动物医院',doctor:'王医生 · 全科',tags:['健康检查','血常规','生化检查'],result:'整体健康状况良好，继续保持规律照护。'}, {date:'2024.08.12',type:'疫苗',name:'年度疫苗接种',hospital:'宠颐生动物医院',doctor:'陈医生 · 预防保健',tags:['疫苗接种','健康管理'],result:'本次接种已完成。'}];
function renderArchive(){let content='';const list=[...state.extraRecords,...(currentPet().id==='doudou'?baseRecords.filter(r=>!recordDeleted(r)):[])].slice(0,3);if(state.archiveTab==='时间轴')content=`<div class="timeline">${list.map((r,i)=>`<button class="timeline-item" data-timeline="${i}"><div class="timeline-date">${esc(r.date)}<span>${r.type}</span></div><article class="${r.name==='皮肤炎（疑似过敏）'||r.name==='年度体检'?'has-thumbnail':''}">${r.name==='皮肤炎（疑似过敏）'?crop(5,.805,.354,.178,.097,'timeline-thumb','参考中的宠物照片'):r.name==='年度体检'?crop(5,.805,.531,.178,.095,'timeline-thumb','参考中的体检报告缩略图'):''}<h2>${esc(r.name)}</h2><p>${esc(r.hospital)}<br>${esc(r.doctor)}</p>${tags(r.tags)}<p class="result">${esc(r.result)}</p></article></button>`).join('')}</div>`;if(state.archiveTab==='检查报告')content=`<section class="section-block"><h2>2025.08.14 · 瑞鹏宠物医院</h2>${reports()}</section>`;if(state.archiveTab==='诊断记录')content=`<button class="section-block full-width left" data-route="visit"><h2>急性胃肠炎</h2><p>2025.08.14 · 瑞鹏宠物医院 · 李医生</p>${tags(['猫科','口服药物','复诊观察'])}<span class="text-link">查看就诊详情 →</span></button><section class="section-block"><h2>皮肤炎（疑似过敏）</h2><p>2025.08.14 · 瑞鹏宠物医院 · 皮肤科</p><p>症状已有明显好转。</p></section>`;if(state.archiveTab==='疫苗驱虫')content=`<section class="section-block"><h2>年度疫苗接种 <span class="complete">已完成</span></h2><p>2024.08.12 · 宠颐生动物医院</p></section><section class="section-block"><h2>驱虫记录</h2><p>暂无已添加的驱虫记录。</p><button class="outline-btn" data-action="add-record">添加记录</button></section>`;scroll.innerHTML=`<div class="archive-pet">${avatar()}<div><h2>豆豆</h2><p>3岁2个月 · 布偶猫 · 5.2 kg</p></div></div><div class="tabs archive-tabs">${['时间轴','检查报告','诊断记录','疫苗驱虫'].map(t=>`<button class="${state.archiveTab===t?'selected':''}" data-archive-tab="${t}">${t}</button>`).join('')}</div><p class="archive-note">${I('heart')}不同医院的记录，都留在豆豆的档案里。</p>${content}<button class="add-button" data-action="add-record">${I('plus')}添加其他医院就诊记录</button>`;}
function timesFor(m){return m.frequency.includes('3')?['08:00','14:00','20:00']:m.frequency.includes('1')?['20:00']:['08:00','20:00'];}
function logFor(m){if(!m.logs)m.logs=Object.fromEntries(timesFor(m).map(t=>[t,t==='08:00'&&m.day>0]));return m.logs;}
function doseRows(m){const logs=logFor(m);return timesFor(m).map(t=>`<div class="dose-row ${logs[t]?'completed':''}">${I(logs[t]?'check':'clock')}<div><b>${t}</b><span>${logs[t]?'已服用':'待服用'}</span></div><button class="dose-btn" data-taken="${m.id}" data-dose="${t}">${logs[t]?'撤销':'已服用'}</button>${!logs[t]?`<button class="dose-remind" data-remind="${m.id}" data-dose="${t}">${m.reminders?.[t]?'已设提醒':'提醒我'}</button>`:''}</div>`).join('');}
function renderMedication(){scroll.innerHTML=`<div class="tabs">${['当前用药','用药历史'].map(t=>`<button class="${state.medTab===t?'selected':''}" data-med-tab="${t}">${t}</button>`).join('')}</div><div class="med-pet">${avatar()}<div><b>${state.medTab==='当前用药'?'今天的照护，按时完成':'每一次照护，都有记录'}</b><p>${state.medTab==='当前用药'?'今天还有 '+state.meds.reduce((n,m)=>n+timesFor(m).filter(t=>!logFor(m)[t]).length,0)+' 项用药待完成':'查看已结束的用药疗程'}</p></div></div>${state.medTab==='当前用药'?state.meds.map((m,i)=>`<article class="med-card"><div class="med-title">${i<2?crop(6,.056,i===0?.322:.591,.155,.062,'drug-photo','参考药品图片，仅作示意'):'<span class="soft-icon">'+I('pill')+'</span>'}<div><h2>${esc(m.name)}</h2><p>${esc(m.method)}</p></div><span class="demo-pill">演示处方</span></div><div class="med-stats"><div><small>单次剂量</small><b>${esc(m.dose)}</b></div><div><small>每日次数</small><b>${esc(m.frequency)}</b></div><div><small>疗程</small><b>${m.days} 天</b></div></div><div class="progress-copy"><span>已用 ${m.day} 天 / 共 ${m.days} 天</span><span>${Math.round(m.day/m.days*100)}%</span></div><div class="progress-track"><i style="width:${m.day/m.days*100}%"></i></div><h3>今天的服药任务</h3>${doseRows(m)}</article>`).join(''):`<section class="section-block"><h2>肠胃护理疗程 <span class="complete">已完成</span></h2><p>2025.05.20–2025.05.26 · 7 天</p><p>历史示例记录 · 按处方完成疗程。</p></section>`}<button class="add-button" data-action="add-med">${I('plus')}添加用药</button><section class="review-card">${I('calendar')}<div><h2>下次复诊提醒</h2><b>${state.review} · ${state.reviewTime}</b><p>瑞鹏宠物医院 · 猫科</p></div><button data-action="review">${I('edit')}</button></section><p class="microcopy centered">药名、图片与剂量为界面演示，不可作为真实用药依据。提醒仅在原型内展示。</p>`;}
function renderProfile(){const p=currentPet();scroll.innerHTML=`<div class="owner-card"><span class="soft-icon">${I('user')}</span><div><h2>我的照护空间</h2><p>陪伴它们，也照顾好每一天</p></div></div><section class="pet-selector"><div class="section-heading"><h2>我的宠物 <small>${petStore.pets.length}只</small></h2><button data-pet-action="add">${I('plus')}添加宠物</button></div><div class="pet-carousel" aria-label="左右滑动选择宠物">${petStore.pets.map(x=>`<article class="pet-slide ${x.id===p.id?'selected':''}" data-pet-id="${x.id}"><button class="pet-card-main" data-pet-edit="${x.id}" aria-label="查看${esc(x.name)}的宠物档案">${avatar(x)}<div><h2>${esc(x.name)}</h2><p>${esc(x.breed)} · ${petAge(x)}</p><small>${x.sex} · ${x.weight} kg</small></div>${I('chevron')}</button><button class="select-pet" data-select-pet="${x.id}" ${x.id===p.id?'aria-current="true"':''}>${I(x.id===p.id?'check':'paw')}${x.id===p.id?'当前照护宠物':'切换到'+esc(x.name)}</button></article>`).join('')}</div><div class="pet-switch-hint"><span>左右滑动切换 · 点击卡片查看档案</span><div>${petStore.pets.map(x=>`<button aria-label="切换到${esc(x.name)}" data-select-pet="${x.id}" class="pet-dot ${x.id===p.id?'selected':''}"></button>`).join('')}</div></div></section><div class="profile-links"><button data-route="petdetail">${I('paw')}宠物基本档案 ${I('chevron')}</button><button data-route="archive">${I('file')}${esc(p.name)}的医疗档案 ${I('chevron')}</button><button data-route="visit">${I('record')}就诊记录 ${I('chevron')}</button><button data-route="medication">${I('pill')}用药与提醒 ${I('chevron')}</button></div><p class="microcopy centered">宠物档案保存在当前浏览器，暂不支持跨设备同步。<br>每只宠物的症状、档案和用药分别管理。</p>`;}
function voice(){modal('语音描述',`<div class="voice-demo">${I('mic')}<p>示例语音</p><blockquote>“豆豆这两天一直吐，吃得少，精神也不太好。”</blockquote><button class="cta" data-action="apply-voice">体验 AI 整理结果</button><p class="microcopy">演示模式：使用这段示例，不录音、不上传声音。</p></div>`)}
function addRecord(){modal('添加其他医院就诊记录',`<form id="record-form" class="entry-form"><label>事件名称<input name="name" required maxlength="40" placeholder="例如：年度体检"></label><label>就诊日期<input name="date" required type="date" value="2025-08-14"></label><label>医院<input name="hospital" required maxlength="40" placeholder="医院名称"></label><div class="form-row"><label>类型<select name="type"><option>就诊</option><option>体检</option><option>疫苗</option></select></label><label>医生 / 科室<input name="doctor" required maxlength="30" placeholder="李医生 · 猫科"></label></div><label>简短结果<input name="result" required maxlength="80" placeholder="记录本次就诊结果"></label><button class="cta" type="submit">保存到医疗档案</button><p class="microcopy">演示数据仅保留在本次预览中。</p></form>`)}
function addMed(){modal('添加用药',`<form id="med-form" class="entry-form"><p class="microcopy">请根据已有处方填写，不自动生成药物或剂量。</p><label>药物名称<input name="name" required maxlength="40" placeholder="填写处方中的药物名称"></label><label>使用方式<input name="method" required maxlength="30" placeholder="按处方填写"></label><div class="form-row"><label>单次剂量<input name="dose" required maxlength="20" placeholder="按处方填写"></label><label>每日次数<select name="frequency"><option>每日 2 次</option><option>每日 1 次</option><option>每日 3 次</option></select></label></div><label>疗程（天）<input name="days" type="number" min="1" max="365" required value="7"></label><button class="cta" type="submit">添加用药计划</button></form>`)}
function reviewModal(){modal('设置复诊提醒',`<form id="review-form" class="entry-form"><div class="detail"><b>瑞鹏宠物医院 · 猫科</b><p>豆豆的复诊安排</p></div><label>日期<input type="date" name="date" required value="${state.review}"></label><label>时间<input type="time" name="time" required value="${state.reviewTime}"></label><button class="cta" type="submit">保存提醒</button><p class="microcopy">原型内提醒，不会发送系统推送。</p></form>`)}
function mapped(key){return ({care:'symptom',record:'visit',archive:'archive',medicine:'medication',pet:'profile',report:'visit',prescription:'medication',advice:'visit'})[key]}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.route){go(b.dataset.route);return;}if(b.dataset.open){if(mapped(b.dataset.open)){go(mapped(b.dataset.open));return;}if(b.dataset.open==='review'){reviewModal();return;}if(b.dataset.open==='notifications'){modal('今日提醒',`<button class="detail full-width left" data-route="medication"><b>20:00 · 晚间用药</b><p>${state.meds.filter(m=>!m.taken).length} 项待完成 →</p></button><button class="detail full-width left" data-action="review"><b>${state.review} · ${state.reviewTime}</b><p>猫科复诊提醒 →</p></button>`);return;}if(b.dataset.open==='weight'){modal('体重记录','<div class="detail"><b>当前体重 5.2 kg</b><p>2025.08.14　5.2 kg<br>2025.07.14　5.1 kg<br>2025.06.14　5.1 kg</p></div>');return;}if(b.dataset.open==='vaccine'){state.archiveTab='疫苗驱虫';go('archive');return;}}
if(b.dataset.nav==='home'){go('home');return;}
if(b.dataset.choice){const k=b.dataset.choice,v=b.dataset.value;if(k==='symptoms')state[k]=state[k].includes(v)?state[k].filter(x=>x!==v):[...state[k],v];else state[k]=v;const top=scroll.scrollTop;render();scroll.scrollTop=top;return;}
if(b.dataset.filter){if(b.dataset.filter==='专科筛选'){toggleSpecialtyDropdown(b);}else{state.filter=b.dataset.filter;render();}return;}
if(b.dataset.specialty){state.specialty=b.dataset.specialty;render();scroll.querySelector('[data-filter="专科筛选"]')?.focus({preventScroll:true});return;}
if(b.dataset.compare){const id=+b.dataset.compare;if(state.compare.includes(id))state.compare=state.compare.filter(x=>x!==id);else if(state.compare.length<2)state.compare.push(id);else{toast('最多对比两家，请先移除一家');return;}const top=scroll.scrollTop;render();scroll.scrollTop=top;return;}
if(b.dataset.archiveTab){state.archiveTab=b.dataset.archiveTab;render();return;}if(b.dataset.medTab){state.medTab=b.dataset.medTab;render();return;}
if(b.dataset.medical){const c=medicalCards[+b.dataset.medical];modal(c[0],`<div class="detail"><b>${c[1]}</b><p>${c[3]}</p></div>`);return;}
if(b.dataset.report!==undefined){const i=+b.dataset.report;modal(['血常规','腹部超声','生化检查'][i],`${crop(4,.052+i*.24,.689,.218,.065,'report-large','参考稿中的报告示意图')}<p>2025.08.14 · 瑞鹏宠物医院</p><p class="microcopy">原型示意图，非真实可判读的检查报告。</p>`);return;}
if(b.dataset.timeline!==undefined){const rec=[...state.extraRecords,...(currentPet().id==='doudou'?baseRecords.filter(r=>!recordDeleted(r)):[])][+b.dataset.timeline];if(rec.visit){go('visit');return;}modal(rec.name,`<div class="detail"><b>${esc(rec.date)} · ${esc(rec.type)}</b><p>${esc(rec.hospital)}<br>${esc(rec.doctor)}</p>${tags(rec.tags)}<p>${esc(rec.result)}</p></div>${rec.detail?`<p class="microcopy">${rec.detail}</p>`:''}`);return;}
if(b.dataset.taken){const m=state.meds.find(m=>m.id===+b.dataset.taken);const t=b.dataset.dose,logs=logFor(m);logs[t]=!logs[t];m.taken=timesFor(m).every(t=>logs[t]);const top=scroll.scrollTop;render();scroll.scrollTop=top;toast(logs[t]?'已记录 '+t+' 用药':'已撤销本次记录');return;}
if(b.dataset.remind){const m=state.meds.find(m=>m.id===+b.dataset.remind);const t=b.dataset.dose;m.reminders=m.reminders||{};m.reminders[t]=!m.reminders[t];const top=scroll.scrollTop;render();scroll.scrollTop=top;toast(m.reminders[t]?'已设置原型内 '+t+' 提醒':'已取消提醒');return;}
const a=b.dataset.action;if(a==='back'){go(state.history.pop()||'home',true);}if(a==='voice')voice();if(a==='apply-voice'){state.symptoms=['呕吐','食欲下降'];state.duration='1–3天';state.appetite='下降';state.energy='稍差';sheet.close();render();toast('已整理，请确认或修改症状信息');}if(a==='next-hospital'){if(!state.symptoms.length||!state.duration||!state.appetite||!state.energy){toast('请补充症状、持续时间、食欲和精神状态');return;}go('hospitals');}if(a==='compare')go('compare');if(a==='clear-filter'){state.specialty='全部';state.filter='综合推荐';render();}if(a==='book'){const h=hospitals.find(h=>h.id===state.recommended);modal('预约就诊',`<form id="booking-form" class="entry-form"><div class="detail"><b>${h.name} · ${h.branch}</b><p>豆豆 · ${state.careMode==='purpose'?esc(state.carePurpose):(state.symptoms.map(esc).join('、')||'健康咨询')}</p></div><label>意向日期<input name="date" type="date" value="2025-08-21" required></label><label>意向时段<select name="slot"><option>上午 10:00</option><option>下午 14:00</option><option>晚上 19:00</option></select></label><p class="microcopy">演示预约，不占用真实医院号源。</p><button class="cta" type="submit">确认演示预约</button></form>`);}if(a==='save-archive'){if(!state.archived)state.extraRecords.unshift({date:'2025.08.14',type:'就诊',name:'急性胃肠炎',hospital:'瑞鹏宠物医院',doctor:'李医生 · 猫科',tags:['食欲下降','偶有呕吐','口服药物'],result:'已制定口服药物与肠胃护理方案。',visit:true});state.archived=true;render();toast('已加入豆豆的医疗档案');}if(a==='review')reviewModal();if(a==='make-plan'){state.medTab='当前用药';go('medication');toast('已展示示例处方的用药计划');}if(a==='add-record')addRecord();if(a==='add-med')addMed();if(b.id==='close')sheet.close();});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f));if(f.id==='record-form'){state.extraRecords.unshift({...d,date:d.date.replaceAll('-','.'),tags:['外院记录'],result:d.result});state.archiveTab='时间轴';sheet.close();render();toast('已添加其他医院的记录');}if(f.id==='med-form'){state.meds.push({...d,id:Date.now(),days:+d.days,day:0,taken:false,remind:false});state.medTab='当前用药';sheet.close();render();toast('用药计划已添加');}if(f.id==='review-form'){state.review=d.date;state.reviewTime=d.time;sheet.close();render();toast('复诊提醒已保存');}if(f.id==='booking-form'){state.booked=true;modal('演示预约已完成',`<div class="booking-success">${I('check')}<h3>豆豆的就医准备已就绪</h3><p>${esc(d.date)} · ${esc(d.slot)}</p><p>请携带症状记录与既往医疗档案。</p><button class="cta" data-route="home">返回首页</button><p class="microcopy">这是交互演示，没有发起真实预约。</p></div>`);}});
sheet.addEventListener('click',e=>{if(e.target===sheet){const r=sheet.getBoundingClientRect();if(e.clientY<r.top||e.clientX<r.left||e.clientX>r.right)sheet.close();}});if(petStore.data[petStore.active])Object.assign(state,petStore.data[petStore.active]);else if(petStore.active!=='doudou')Object.assign(state,{meds:[],extraRecords:[],review:''});render();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'pawcare_navigate',title:'打开 PawCare 页面',description:'打开作品集原型的页面；不会预约医院或修改医疗数据。',inputSchema:{type:'object',properties:{page:{type:'string',enum:['home','symptom','hospitals','visit','archive','medication','profile']}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!['home','symptom','hospitals','visit','archive','medication','profile'].includes(input.page))throw new Error('Invalid page');go(input.page);return {page:state.route,demo:true};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}
function renderPetDetail(){const p=currentPet();scroll.innerHTML=`<div class="pet-detail-hero">${avatar()}<h2>${esc(p.name)}</h2><p>${esc(p.breed)} · ${petAge(p)}</p></div><section class="section-block"><div class="section-heading"><h2>基本信息</h2><button data-pet-action="edit">${I('edit')}编辑资料</button></div><dl class="pet-details">${[['宠物类型',p.species],['品种',p.breed],['年龄',petAge(p)],['性别',p.sex],['绝育状态',p.neutered],['体重',p.weight+' kg']].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></section><section class="section-block"><h2>照护备注</h2><p>${esc(p.notes||'还没有备注，可以记录过敏史、就诊习惯或照护偏好。')}</p></section><button class="add-button" data-route="archive">${I('file')}查看${esc(p.name)}的医疗档案</button><p class="microcopy centered">资料用于当前宠物的就医与照护。</p>`;footer(`<button class="cta" data-pet-action="edit">${I('edit')}编辑宠物档案</button>`);}
function petForm(isNew=false){const p=isNew?{name:'',species:'狗',breed:'边境牧羊犬',years:0,months:0,sex:'未知',neutered:'未知',weight:'',notes:'',photo:'dog'}:currentPet();modal(isNew?'添加宠物档案':'编辑宠物档案',`<form id="pet-form" class="entry-form" data-new="${isNew}"><label>昵称<input name="name" required maxlength="16" value="${esc(p.name)}" placeholder="宠物的名字"></label><div class="form-row"><label>宠物类型<select name="species">${['猫','狗'].map(v=>`<option ${p.species===v?'selected':''}>${v}</option>`).join('')}</select></label><label>品种<input name="breed" list="breed-options" required maxlength="30" value="${esc(p.breed)}"><datalist id="breed-options">${['边境牧羊犬','布偶猫','金毛寻回犬','中华田园犬','英国短毛猫','中华田园猫','其他'].map(v=>`<option value="${v}">`).join('')}</datalist></label></div><div class="form-row"><label>年龄（岁）<input name="years" type="number" min="0" max="40" step="1" required value="${p.years}"></label><label>月龄（0–11月）<input name="months" type="number" min="0" max="11" step="1" required value="${p.months}"></label></div><div class="form-row"><label>性别<select name="sex">${['公','母','未知'].map(v=>`<option ${p.sex===v?'selected':''}>${v}</option>`).join('')}</select></label><label>绝育状态<select name="neutered">${['已绝育','未绝育','未知'].map(v=>`<option ${p.neutered===v?'selected':''}>${v}</option>`).join('')}</select></label></div><label>体重（kg）<input name="weight" type="number" min="0.1" max="120" step="0.1" required value="${p.weight}" placeholder="例如 18.5"></label><label>档案照片<select name="photo"><option value="dog" ${p.photo==='dog'?'selected':''}>边牧示例照片</option><option value="cat" ${p.photo==='cat'?'selected':''}>布偶猫示例照片</option><option value="none" ${p.photo==='none'?'selected':''}>使用默认图标</option></select></label><label>照护备注<textarea name="notes" maxlength="300" placeholder="过敏史、就诊习惯或照护偏好">${esc(p.notes)}</textarea></label><button class="cta" type="submit">${isNew?'创建并切换到这只宠物':'保存资料'}</button><p class="microcopy">照片为示例素材；信息仅保存在当前浏览器。</p></form>`);}
function render(){renderOriginal();const p=currentPet();
if(state.route==='archive'&&p.id!=='doudou'){if(state.archiveTab==='时间轴'&&!state.extraRecords.length)$('.timeline').innerHTML=`<div class="empty-pet-state">${I('file')}<h2>还没有医疗记录</h2><p>为${esc(p.name)}添加第一条就诊、体检或疫苗记录。</p></div>`;if(state.archiveTab!=='时间轴'){scroll.innerHTML=`<div class="archive-pet">${avatar()}<div><h2>${esc(p.name)}</h2><p>${esc(p.breed)} · ${petAge(p)} · ${p.weight} kg</p></div></div><div class="tabs archive-tabs">${['时间轴','检查报告','诊断记录','疫苗驱虫'].map(t=>`<button class="${state.archiveTab===t?'selected':''}" data-archive-tab="${t}">${t}</button>`).join('')}</div><div class="empty-pet-state">${I('file')}<h2>暂无${state.archiveTab}</h2><p>当前宠物还未添加此类资料。</p></div><button class="add-button" data-action="add-record">${I('plus')}添加其他医院就诊记录</button>`;}}
if(state.route==='visit'&&p.id!=='doudou'){scroll.innerHTML=petMini()+`<div class="empty-pet-state">${I('record')}<h2>暂无就诊记录</h2><p>添加${esc(p.name)}的就诊信息，方便下次查阅。</p><button class="cta" data-action="add-record">添加就诊记录</button></div>`;$('#route-footer')?.remove();}
if(state.route==='medication'&&p.id!=='doudou'){if(state.medTab==='用药历史')scroll.querySelector('.section-block').innerHTML='<h2>暂无用药历史</h2><p>完成的用药疗程会保存在这里。</p>';if(!state.meds.length&&state.medTab==='当前用药')scroll.querySelector('.add-button').insertAdjacentHTML('beforebegin','<div class="empty-pet-state">'+I('pill')+'<h2>目前没有用药计划</h2><p>如有医生处方，可以添加用药和提醒。</p></div>');if(!state.review)scroll.querySelector('.review-card').innerHTML=I('calendar')+'<div><h2>尚未设置复诊提醒</h2><p>需要时再添加日期与时间。</p></div><button data-action="review" aria-label="添加复诊提醒">'+I('plus')+'</button>';}
const walker=document.createTreeWalker(header,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode())n.nodeValue=n.nodeValue.replaceAll('豆豆',p.name);
if(state.route!=='profile'&&state.route!=='petdetail'){const walker=document.createTreeWalker(scroll,NodeFilter.SHOW_TEXT);while(n=walker.nextNode()){n.nodeValue=n.nodeValue.replaceAll('豆豆',p.name).replaceAll('布偶猫 · 3岁2个月',p.breed+' · '+petAge(p)).replaceAll('3岁2个月 · 布偶猫 · 5.2 kg',petAge(p)+' · '+p.breed+' · '+p.weight+' kg');}}
if(state.route==='home'){const c=$('.pet .cat');c.classList.toggle('dog-avatar',p.photo==='dog');c.classList.toggle('plain-avatar',p.photo==='none');$('.pet-copy>p').textContent=p.breed+'　'+petAge(p)+'　'+p.sex;$('.metrics button:first-child b').textContent=p.weight+' kg';$('.pet-name').dataset.open='petdetail';if(p.id!=='doudou'){$('.health').innerHTML=I('heart')+'健康待记录';$('.metrics button:nth-child(2) b').textContent='待添加';$('.metrics button:nth-child(2) time').textContent='暂无接种记录';$('.metrics button:last-child b').textContent=state.review?state.review.slice(5).replace('-','月')+'日':'未设置';if(!state.meds.length)$('.reminder:first-of-type');const reminders=$('.reminders');if(!state.meds.length)reminders.innerHTML='<div class="section-heading"><h2>今日提醒</h2></div><p class="microcopy">目前没有用药任务。可为'+esc(p.name)+'添加用药或复诊提醒。</p><button class="outline-btn" data-open="medicine">管理提醒</button>';$('.recent').innerHTML='<div class="section-heading"><h2>最近一次就诊</h2></div><p class="microcopy">'+(state.extraRecords.length?esc(state.extraRecords[0].name):'暂无就诊记录，添加后会显示在这里。')+'</p><button class="outline-btn" data-open="archive">查看医疗档案</button>';}}
if(state.route==='profile'){const el=$('.pet-carousel');requestAnimationFrame(()=>{const active=el.querySelector('[data-pet-id="'+p.id+'"]');el.scrollLeft=active.offsetLeft-el.firstElementChild.offsetLeft;let ready=false;setTimeout(()=>ready=true,300);let timer;el.addEventListener('scroll',()=>{if(!ready)return;clearTimeout(timer);timer=setTimeout(()=>{if(!el.isConnected||state.route!=='profile')return;const cards=[...el.children];const x=el.scrollLeft;const first=cards[0].offsetLeft;const near=cards.reduce((a,b)=>Math.abs(b.offsetLeft-first-x)<Math.abs(a.offsetLeft-first-x)?b:a);if(near.dataset.petId!==petStore.active)switchPet(near.dataset.petId);},220);},{passive:true});});}
icons();savePets();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.selectPet)switchPet(b.dataset.selectPet);if(b.dataset.petEdit){switchPet(b.dataset.petEdit);go('petdetail');}if(b.dataset.petAction)petForm(b.dataset.petAction==='add');if(b.dataset.open==='petdetail')go('petdetail');});
document.addEventListener('submit',e=>{if(e.target.id!=='pet-form')return;e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f));if(!d.name.trim()||!d.breed.trim())return;const p={...d,name:d.name.trim(),breed:d.breed.trim(),years:+d.years,months:+d.months,weight:+d.weight};if(f.dataset.new==='true'){savePets();p.id='pet-'+Date.now();petStore.pets.push(p);switchPet(p.id);}else Object.assign(currentPet(),p);sheet.close();go('petdetail');savePets();toast('宠物档案已保存');});


function accountData(){try{return JSON.parse(localStorage.getItem('pawcare-account-v1'))||{name:'宠物照护者',phone:'',city:'',bio:'',reminders:true,reducedMotion:false};}catch{return {name:'宠物照护者',phone:'',city:'',bio:'',reminders:true,reducedMotion:false};}}
function saveAccount(d){try{localStorage.setItem('pawcare-account-v1',JSON.stringify(d));}catch{} }
function openAccount(){const a=accountData();modal('我的照护空间',`<div class="account-summary"><span class="soft-icon">${I('user')}</span><div><h3>${esc(a.name)}</h3><p>${esc(a.city||'完善个人信息，让照护更有条理')}</p></div></div><div class="account-menu"><button data-account="edit">${I('user')}<div><b>个人资料</b><small>昵称、联系方式与所在城市</small></div>${I('chevron')}</button><button data-account="wallet">${I('record')}<div><b>我的钱包</b><small>余额与交易记录</small></div>${I('chevron')}</button><button data-account="settings">${I('filter')}<div><b>设置</b><small>提醒偏好与使用说明</small></div>${I('chevron')}</button></div>`);}
function accountEdit(){const a=accountData();modal('个人资料',`<form id="account-form" class="entry-form"><label>昵称<input name="name" required maxlength="20" value="${esc(a.name)}" placeholder="怎么称呼你"></label><label>联系电话（选填）<input name="phone" type="tel" maxlength="25" value="${esc(a.phone)}" placeholder="填写联系电话"></label><label>所在城市（选填）<input name="city" maxlength="40" value="${esc(a.city)}" placeholder="例如：上海"></label><label>个人简介（选填）<textarea name="bio" maxlength="200" placeholder="记录你的养宠经历">${esc(a.bio)}</textarea></label><button class="cta" type="submit">保存个人资料</button><button class="account-return" type="button" data-account="home">返回照护空间</button><p class="microcopy">仅保存在当前浏览器</p></form>`);}
function wallet(){modal('我的钱包',`<section class="wallet-balance"><p>可用余额（演示）</p><h3><small>¥</small> 0.00</h3><span>尚未接入支付服务</span></section><section class="section-block"><h2>交易记录</h2><div class="wallet-empty">${I('record')}<b>暂无交易记录</b><p>消费与退款记录将显示在这里。</p></div></section><p class="microcopy centered">演示钱包 · 不支持真实交易</p><button class="account-return" data-account="home">返回照护空间</button>`);}
function accountSettings(){const a=accountData();modal('设置',`<div class="account-settings"><label><div><b>照护提醒</b><small>原型内用药与复诊提醒偏好</small></div><input type="checkbox" role="switch" data-pref="reminders" ${a.reminders?'checked':''}></label><label><div><b>减少动态效果</b><small>降低过渡动画与平滑滚动</small></div><input type="checkbox" role="switch" data-pref="reducedMotion" ${a.reducedMotion?'checked':''}></label></div><div class="account-menu"><button data-account="privacy">${I('shield')}<div><b>隐私与数据</b><small>查看信息的保存方式</small></div>${I('chevron')}</button><button data-account="about">${I('heart')}<div><b>关于 PawCare</b><small>作品集交互原型</small></div>${I('chevron')}</button></div><button class="account-return" data-account="home">返回照护空间</button>`);}
function applyAccountPrefs(){document.documentElement.classList.toggle('reduce-motion',!!accountData().reducedMotion);}
function decorateAccount(){const owner=document.querySelector('.owner-card');if(owner){owner.setAttribute('role','button');owner.setAttribute('tabindex','0');owner.setAttribute('aria-label','进入我的照护空间');owner.dataset.account='home';if(!owner.querySelector('.owner-arrow'))owner.insertAdjacentHTML('beforeend','<span class="owner-arrow">'+I('chevron')+'</span>');const a=accountData();owner.querySelector('p').textContent=a.name==='宠物照护者'?'个人资料 · 钱包 · 设置':a.name+' · 个人资料与设置';}applyAccountPrefs();}
const accountObserver=new MutationObserver(()=>{const owner=document.querySelector('.owner-card');if(owner&&!owner.dataset.account)decorateAccount();});accountObserver.observe(scroll,{childList:true,subtree:true});decorateAccount();
document.addEventListener('click',e=>{const el=e.target.closest('[data-account]');if(!el)return;const k=el.dataset.account;if(k==='home')openAccount();if(k==='edit')accountEdit();if(k==='wallet')wallet();if(k==='settings')accountSettings();if(k==='privacy')modal('隐私与数据',`<div class="detail"><b>数据保存在当前浏览器</b><p>个人资料、宠物档案和照护偏好通过浏览器本地存储保存，暂不支持云端同步。清除网站数据会移除这些本地记录。</p><p>本原型未接入支付、短信验证或服务器账户。</p></div><button class="account-return" data-account="settings">返回设置</button>`);if(k==='about')modal('关于 PawCare',`<div class="detail"><b>PawCare｜宠物就医与健康管理平台</b><p>帮助宠物主人整理就医信息，持续管理宠物的医疗档案和日常照护。</p><p>版本 1.0 · 作品集交互原型</p></div><button class="account-return" data-account="settings">返回设置</button>`);});
document.addEventListener('keydown',e=>{if(e.target.matches('.owner-card')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openAccount();}});
document.addEventListener('change',e=>{const k=e.target.dataset.pref;if(!k)return;const a=accountData();a[k]=e.target.checked;saveAccount(a);applyAccountPrefs();toast('偏好已保存');});
document.addEventListener('submit',e=>{if(e.target.id!=='account-form')return;e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(!d.name.trim())return;saveAccount({...accountData(),...d,name:d.name.trim()});decorateAccount();openAccount();toast('个人资料已保存');});
function careChoice(){modal('这次想为宠物做什么？',`<div class="care-choice-intro">为${esc(currentPet().name)}选择本次就医目的</div><div class="care-choice-options"><button data-care-path="symptoms"><span class="soft-icon">${I('stethoscope')}</span><div><h3>发现异常，还不清楚原因</h3><p>整理症状，辅助筛选医院。</p><small>症状整理 → 医院推荐</small></div>${I('chevron')}</button><button data-care-path="purpose"><span class="soft-icon">${I('calendar')}</span><div><h3>已经知道要去做什么</h3><p>体检 · 疫苗 · 驱虫 · 复诊</p><small>选择服务 → 筛选医院</small></div>${I('chevron')}</button></div><p class="microcopy centered">演示体验 · AI 整理不代替诊断</p>`);}
function carePurpose(){modal('选择就医需求',`<p class="care-choice-intro">这次要带${esc(currentPet().name)}去医院做什么？</p><div class="purpose-grid">${[['体检','shield','了解近期健康状况'],['疫苗接种','clipboard','安排常规接种'],['驱虫','heart','咨询与安排驱虫'],['复诊','calendar','继续既有诊疗'],['其他明确需求','record','填写你需要的服务']].map(([n,ic,t])=>`<button data-care-purpose="${n}">${I(ic)}<b>${n}</b><small>${t}</small></button>`).join('')}</div><button class="account-return" data-care-back>返回就医方式选择</button>`);}
function beginPurpose(purpose){state.careMode='purpose';state.carePurpose=purpose;state.compare=[];state.specialty='全部';state.filter='综合推荐';go('hospitals');}
const careOriginalRenderHospitals=renderHospitals;
renderHospitals=function(){careOriginalRenderHospitals();if(state.careMode==='purpose'){const note=scroll.querySelector('.need-note');note.innerHTML=I('calendar')+'<div>'+esc(currentPet().name)+' · '+esc(state.carePurpose)+'<small>按服务需求选择医院，无需填写症状</small></div>';note.insertAdjacentHTML('afterend','<button class="change-purpose" data-change-purpose>更改就医需求</button>');}};
const careOriginalRenderCompare=renderCompare;
renderCompare=function(){careOriginalRenderCompare();if(state.careMode==='purpose'){const selected=state.compare.map(id=>hospitals.find(h=>h.id===id));const preferred=state.carePurpose==='体检'?(selected.find(h=>h.tags.includes('体检中心'))||selected[0]):selected[0];if(preferred){state.recommended=preferred.id;const p=scroll.querySelector('.recommendation p');p.textContent=state.carePurpose==='体检'&&preferred.tags.includes('体检中心')?preferred.name+'设有体检服务，更贴合本次需求；具体套餐请向医院确认。':preferred.name+'可作为本次'+state.carePurpose+'的意向医院，服务项目与可预约时间需向医院确认。';}}};
document.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.open==='care'){e.preventDefault();e.stopImmediatePropagation();careChoice();return;}if(button.dataset.carePath){if(button.dataset.carePath==='symptoms'){state.careMode='symptoms';state.carePurpose='';go('symptom');}else carePurpose();return;}if(button.dataset.carePurpose){if(button.dataset.carePurpose==='其他明确需求'){modal('其他就医需求','<form id="care-purpose-form" class="entry-form"><label>你希望医院提供什么服务？<input name="purpose" required maxlength="40" placeholder="例如：术后拆线、口腔检查"></label><button class="cta" type="submit">下一步：选择医院</button></form>');}else beginPurpose(button.dataset.carePurpose);return;}if(button.hasAttribute('data-care-back'))careChoice();if(button.hasAttribute('data-change-purpose'))carePurpose();},true);
document.addEventListener('submit',e=>{if(e.target.id!=='care-purpose-form')return;e.preventDefault();const value=new FormData(e.target).get('purpose').trim();if(value)beginPurpose(value);});
const previousCarePurpose=carePurpose;
function lastVisitForPet(){if(currentPet().id==='doudou')return {name:'瑞鹏宠物医院',branch:'万象城分院',date:'2025.08.14',doctor:'李医生 · 猫科',hospitalId:1};const rec=state.extraRecords.find(r=>r.type==='就诊');if(!rec)return null;return {name:rec.hospital,branch:'',date:rec.date,doctor:rec.doctor,hospitalId:hospitals.find(h=>rec.hospital.includes(h.name))?.id};}
carePurpose=function(){previousCarePurpose();const v=lastVisitForPet();const block=v?`<section class="last-visit-shortcut"><div class="section-heading"><h2>熟悉的医院，继续照护</h2></div><button data-last-hospital><span class="soft-icon">${I('stethoscope')}</span><div><b>预约上次就诊的医院</b><strong>${esc(v.name)}${v.branch?'（'+esc(v.branch)+'）':''}</strong><small>上次就诊 ${esc(v.date)} · ${esc(v.doctor)}</small></div>${I('chevron')}</button></section>`:`<p class="no-last-visit">暂无上次就诊医院，可先按下方服务需求选择。</p>`;$('#sheet-body .care-choice-intro').insertAdjacentHTML('afterend',block);};
document.addEventListener('click',e=>{if(!e.target.closest('[data-last-hospital]'))return;const v=lastVisitForPet();if(!v)return;modal('预约上次就诊医院',`<form id="repeat-booking-form" class="entry-form"><div class="detail"><b>${esc(v.name)}${v.branch?' · '+esc(v.branch):''}</b><p>${esc(currentPet().name)} · 上次就诊 ${esc(v.date)}<br>${esc(v.doctor)}</p></div><label>本次就医目的<select name="purpose"><option>复诊</option><option>体检</option><option>疫苗接种</option><option>驱虫</option><option>其他明确需求</option></select></label><label>意向日期<input name="date" type="date" required value="${state.review||'2025-08-21'}"></label><label>意向时段<select name="slot"><option>上午 10:00</option><option>下午 14:00</option><option>晚上 19:00</option></select></label><p class="microcopy">演示预约，具体服务与时段需由医院确认，不占用真实号源。</p><button class="cta" type="submit">确认演示预约</button><button class="account-return" type="button" data-change-purpose>返回就医需求</button></form>`);});
document.addEventListener('submit',e=>{if(e.target.id!=='repeat-booking-form')return;e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),v=lastVisitForPet();state.careMode='purpose';state.carePurpose=d.purpose;state.booked=true;savePets();modal('演示预约已完成',`<div class="booking-success">${I('check')}<h3>${esc(currentPet().name)}的就医准备已就绪</h3><div class="detail"><b>${esc(v.name)}${v.branch?' · '+esc(v.branch):''}</b><p>${esc(d.purpose)}<br>${esc(d.date)} · ${esc(d.slot)}</p></div><p>记得携带既往报告与用药记录。</p><button class="cta" data-route="home">返回首页</button><p class="microcopy">这是交互演示，没有发起真实预约。</p></div>`);});
const visitBeforeVoice=renderVisit;
renderVisit=function(){visitBeforeVoice();const mini=scroll.querySelector('.pet-mini');mini.insertAdjacentHTML('afterend',`<button class="voice-entry" data-visit-voice>${I('mic')}<div><b>语音整理诊断记录</b><small>复述医生的诊断与医嘱，整理后确认保存</small></div>${I('chevron')}</button>`);};
function visitVoice(){modal('语音整理诊断记录',`<div class="voice-demo">${I('mic')}<p>请描述医生已经给出的诊断和医嘱</p><blockquote>“医生说是急性胃肠炎，需要按处方口服药物，注意肠胃护理和饮食调整，观察食欲和精神状态，反复就及时复诊。”</blockquote><button class="cta" data-visit-transcribe>体验 AI 整理</button><p class="microcopy">示例语音 · 不录音、不上传。仅整理医嘱，不生成诊断或剂量。</p></div>`);}
function visitVoiceDraft(){modal('确认诊断记录',`<form id="voice-visit-form" class="entry-form"><p class="microcopy">这是待确认草稿，请对照医生的真实结论修改后保存。</p><label>就诊原因<textarea name="reason" required maxlength="300">食欲下降、偶有呕吐、精神状态一般</textarea></label><label>医生诊断<input name="diagnosis" required maxlength="100" value="急性胃肠炎"></label><label>治疗方案<textarea name="treatment" required maxlength="500">按处方口服药物，配合肠胃护理与饮食调整。</textarea></label><label>医生建议<textarea name="advice" required maxlength="500">观察食欲和精神状态，如症状反复及时复诊。</textarea></label><label>就诊日期<input name="date" type="date" required value="2025-08-14"></label><label>医院<input name="hospital" required maxlength="80" value="瑞鹏宠物医院（万象城分院）"></label><button class="cta" type="submit">确认并保存到诊断记录</button><p class="microcopy">保存到${esc(currentPet().name)}的档案；不会覆盖原有就诊记录。</p></form>`);}
document.addEventListener('click',e=>{if(e.target.closest('[data-visit-voice]'))visitVoice();if(e.target.closest('[data-visit-transcribe]'))visitVoiceDraft();});
document.addEventListener('submit',e=>{if(e.target.id!=='voice-visit-form')return;e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(!d.diagnosis.trim())return;state.extraRecords.unshift({date:d.date.replaceAll('-','.'),type:'就诊',name:d.diagnosis.trim(),hospital:d.hospital,doctor:'医生信息待补充',tags:['语音整理','已确认'],result:d.advice,voiceDetails:d});savePets();sheet.close();toast('诊断记录已保存到当前宠物档案');modal('诊断记录已保存',`<div class="detail"><b>${esc(d.diagnosis)}</b><p>${esc(currentPet().name)} · ${esc(d.date)}<br>${esc(d.hospital)}</p><p>已保留就诊原因、治疗方案与医生建议。</p></div><button class="cta" data-view-voice-record>查看诊断记录</button>`);});
const archiveBeforeVoice=renderArchive;
renderArchive=function(){archiveBeforeVoice();if(state.archiveTab==='诊断记录'){const records=state.extraRecords.filter(r=>r.voiceDetails);const tab=scroll.querySelector('.archive-note');if(tab)tab.insertAdjacentHTML('afterend',records.map((r)=>`<button class="section-block full-width left" data-saved-voice="${state.extraRecords.indexOf(r)}"><h2>${esc(r.name)}</h2><p>${esc(r.date)} · ${esc(r.hospital)}</p>${tags(['语音整理','已确认'])}<span class="text-link">查看完整整理记录 →</span></button>`).join(''));}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-view-voice-record')){state.archiveTab='诊断记录';go('archive');}if(b.dataset.savedVoice!==undefined){const r=state.extraRecords[+b.dataset.savedVoice],d=r.voiceDetails;modal('诊断记录',`<div class="detail"><b>${esc(r.date)} · ${esc(r.hospital)}</b></div>${[['就诊原因',d.reason],['医生诊断',d.diagnosis],['治疗方案',d.treatment],['医生建议',d.advice]].map(([k,v])=>`<div class="detail"><b>${k}</b><p>${esc(v)}</p></div>`).join('')}<p class="microcopy">来自示例语音，经用户确认保存。</p>`);}});
const petRenderBeforeVisitVoice=render;
render=function(){petRenderBeforeVisitVoice();if(state.route==='visit'&&!scroll.querySelector('[data-visit-voice]')){scroll.insertAdjacentHTML('afterbegin',`<button class="voice-entry" data-visit-voice>${I('mic')}<div><b>语音整理诊断记录</b><small>根据医生已有结论整理就诊记录</small></div>${I('chevron')}</button>`);}if(state.route==='archive'&&state.archiveTab==='诊断记录'&&currentPet().id!=='doudou'){const records=state.extraRecords.filter(r=>r.voiceDetails);if(records.length){scroll.querySelector('.empty-pet-state')?.remove();scroll.querySelector('.archive-tabs').insertAdjacentHTML('afterend',records.map(r=>`<button class="section-block full-width left" data-saved-voice="${state.extraRecords.indexOf(r)}"><h2>${esc(r.name)}</h2><p>${esc(r.date)} · ${esc(r.hospital)}</p>${tags(['语音整理','已确认'])}<span class="text-link">查看完整整理记录 →</span></button>`).join(''));}}};
// Confirmed voice records remain attached to the visit and its prescription.
let activeVoiceVisit=null;
const visitWithVoiceBase=render;
render=function(){visitWithVoiceBase();const r=state.extraRecords.find(r=>r.voiceDetails&&r.recordId===activeVoiceVisit);if(state.route==='visit'&&r){const d=r.voiceDetails;scroll.innerHTML=`<section class="visit-header">${hospitalPhoto(hospitals[0])}<div><h2>${esc(r.hospital)}</h2><p>${esc(r.date)}</p><span>语音整理 · 已确认</span></div></section>${petMini()}<button class="voice-entry" data-visit-voice>${I('mic')}<div><b>语音整理诊断记录</b><small>补充另一条就诊记录</small></div>${I('chevron')}</button>${[['就诊原因',d.reason],['诊断结果',d.diagnosis],['治疗方案',d.treatment],['医生建议',d.advice]].map(([k,v])=>`<section class="section-block"><h2>${k}</h2><p>${esc(v)}</p>${k==='治疗方案'?`<div class="prescription-summary"><b>${esc(d.drugName)}</b><p>单次 ${esc(d.dose)} · 每日 ${d.frequency} 次 · ${d.days} 天</p></div>`:''}</section>`).join('')}<p class="microcopy centered">处方为演示信息，请以医生真实处方为准。</p>`;footer(`<div class="visit-footer"><button class="outline-btn" data-route="archive">${I('check')}已保存档案</button><button class="outline-btn" data-action="review">${I('calendar')}设置复诊提醒</button><button class="cta" data-action="make-plan">生成用药计划</button></div>`);}};
const oldVoiceDraft=visitVoiceDraft;
visitVoiceDraft=function(){oldVoiceDraft();const form=$('#voice-visit-form');form.querySelector('[type="submit"]').insertAdjacentHTML('beforebegin',`<fieldset class="prescription-fields"><legend>处方信息 · 请核对医生处方</legend><label>药物名称<input name="drugName" required maxlength="60" value="处方口服药 A（演示）"></label><label>单次剂量<input name="dose" required maxlength="40" value="按医生处方"></label><div class="form-row"><label>每日次数<select name="frequency"><option value="1">1 次</option><option value="2" selected>2 次</option><option value="3">3 次</option></select></label><label>疗程（天）<input name="days" type="number" min="1" max="365" required value="7"></label></div><p class="microcopy">示例语音未提供具体药名或剂量，不自动推断；演示药名需按真实处方替换。</p></fieldset>`);form.querySelector('[type="submit"]').textContent='确认并返回就诊详情';};
function planSetup(){const r=state.extraRecords.find(r=>r.recordId===activeVoiceVisit&&r.voiceDetails);const d=r?.voiceDetails||{drugName:'处方口服药 A（演示）',dose:'按医生处方',frequency:'2',days:'7'};const count=+d.frequency||2;const times=count===1?['20:00']:count===2?['08:00','20:00']:['08:00','14:00','20:00'];modal('用药设置',`<form id="visit-plan-form" class="entry-form"><div class="detail"><b>${esc(d.drugName)}</b><p>${esc(currentPet().name)} · 单次 ${esc(d.dose)}<br>每日 ${count} 次 · 疗程 ${d.days} 天</p></div><p>设置每天的服药时间</p>${times.map((t,i)=>`<label>第 ${i+1} 次服药时间<input type="time" name="time${i}" required value="${t}"></label>`).join('')}<label class="plan-reminder"><input type="checkbox" name="remind" checked>开启用药提醒</label><button class="cta" type="submit">确认生成用药计划</button><p class="microcopy">仅在原型内保存提醒设置，不发送系统推送。</p></form>`);}
document.addEventListener('submit',e=>{if(e.target.id==='voice-visit-form'){e.preventDefault();e.stopImmediatePropagation();const d=Object.fromEntries(new FormData(e.target));if(!d.diagnosis.trim()||!d.drugName.trim())return;const id='voice-'+Date.now();state.extraRecords.unshift({recordId:id,date:d.date.replaceAll('-','.'),type:'就诊',name:d.diagnosis.trim(),hospital:d.hospital,doctor:'医生信息待补充',tags:['语音整理','已确认'],result:d.advice,voiceDetails:d});activeVoiceVisit=id;savePets();sheet.close();go('visit');toast('已确认，查看本次就诊详情');}
if(e.target.id==='visit-plan-form'){e.preventDefault();e.stopImmediatePropagation();const f=e.target,v=Object.fromEntries(new FormData(f)),r=state.extraRecords.find(r=>r.recordId===activeVoiceVisit&&r.voiceDetails),d=r?.voiceDetails||{drugName:'处方口服药 A（演示）',dose:'按医生处方',frequency:'2',days:'7'};const schedule=Array.from({length:+d.frequency},(_,i)=>v['time'+i]);if(new Set(schedule).size!==schedule.length){toast('请为每次服药设置不同的时间');return;}const source=activeVoiceVisit||'default-visit';const med={id:Date.now(),sourceVisit:source,name:d.drugName,method:'口服 · 按处方',dose:d.dose,frequency:'每日 '+d.frequency+' 次',days:+d.days,day:0,taken:false,schedule:schedule.sort(),logs:Object.fromEntries(schedule.map(t=>[t,false])),reminders:Object.fromEntries(schedule.map(t=>[t,!!v.remind]))};const old=state.meds.findIndex(m=>m.sourceVisit===source);if(old>=0){modal('该就诊已生成用药计划',`<p>为避免重复服药任务，请在用药管理中查看已有计划。</p><button class="cta" data-route="medication">查看用药计划</button>`);return;}state.meds.push(med);savePets();sheet.close();go('medication');toast('用药计划已生成');}},true);
const originalTimesFor=timesFor;timesFor=function(m){return m.schedule?.length?m.schedule:originalTimesFor(m);};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.action==='make-plan'){e.preventDefault();e.stopImmediatePropagation();planSetup();}if(b.dataset.savedVoice!==undefined){const r=state.extraRecords[+b.dataset.savedVoice];if(r?.recordId){e.preventDefault();e.stopImmediatePropagation();activeVoiceVisit=r.recordId;go('visit');}}if(b.dataset.timeline!==undefined){const r=[...state.extraRecords,...(currentPet().id==='doudou'?baseRecords.filter(r=>!recordDeleted(r)):[])][+b.dataset.timeline];if(r?.recordId){e.preventDefault();e.stopImmediatePropagation();activeVoiceVisit=r.recordId;go('visit');}}},true);
function medicationSettings(id){const m=state.meds.find(m=>m.id===id);if(!m)return;modal('修改用药设置',`<form id="edit-med-schedule" class="entry-form" data-med-id="${m.id}"><div class="detail"><b>${esc(m.name)}</b><p>单次剂量：${esc(m.dose)} · 疗程 ${m.days} 天</p></div><label>每日次数<select name="count">${[1,2,3,4].map(n=>`<option value="${n}" ${timesFor(m).length===n?'selected':''}>每日 ${n} 次</option>`).join('')}</select></label><div id="edit-dose-times">${timesFor(m).map((t,i)=>doseTimeField(t,i,!!m.reminders?.[t])).join('')}</div><button class="cta" type="submit">保存用药设置</button><p class="microcopy">按处方设置次数；已完成记录保留。</p></form>`);}
function doseTimeField(t,i,remind){return `<div class="edit-dose-setting"><label>第 ${i+1} 次时间<input type="time" name="time${i}" required value="${t}"></label><label class="plan-reminder"><input type="checkbox" name="remind${i}" ${remind?'checked':''}>提醒我</label></div>`;}
const renderBeforeMedSettings=render;
render=function(){renderBeforeMedSettings();if(state.route==='medication'&&state.medTab==='当前用药'){scroll.querySelectorAll('.med-card').forEach((card,i)=>{const m=state.meds[i];card.querySelector('.med-title').insertAdjacentHTML('afterend',`<button class="med-settings-link" data-med-settings="${m.id}">${I('clock')}用药设置 ${I('chevron')}</button>`);if(m.completedHistory?.length)card.insertAdjacentHTML('beforeend',`<details class="past-dose-records"><summary>已完成记录（${m.completedHistory.length}）</summary>${m.completedHistory.map(t=>`<p>${esc(t)} · 已服用</p>`).join('')}</details>`);});}};
document.addEventListener('click',e=>{const b=e.target.closest('[data-med-settings]');if(b)medicationSettings(+b.dataset.medSettings);});
document.addEventListener('change',e=>{if(e.target.name!=='count'||e.target.form?.id!=='edit-med-schedule')return;const holder=$('#edit-dose-times'),old=[...holder.querySelectorAll('input[type="time"]')].map((x,i)=>({time:x.value,remind:!!holder.querySelector('[name="remind'+i+'"]').checked})),count=+e.target.value,defaults={1:['20:00'],2:['08:00','20:00'],3:['08:00','14:00','20:00'],4:['08:00','12:00','16:00','20:00']}[count];holder.innerHTML=Array.from({length:count},(_,i)=>doseTimeField(old[i]?.time||defaults[i],i,old[i]?.remind??true)).join('');});
document.addEventListener('submit',e=>{if(e.target.id!=='edit-med-schedule')return;e.preventDefault();const form=e.target,m=state.meds.find(m=>m.id===+form.dataset.medId),d=Object.fromEntries(new FormData(form));if(!m)return;const times=Array.from({length:+d.count},(_,i)=>d['time'+i]);if(new Set(times).size!==times.length){toast('服药时间不能重复，请调整后保存');return;}const oldLogs=logFor(m);m.completedHistory=[...new Set([...(m.completedHistory||[]),...Object.keys(oldLogs).filter(t=>oldLogs[t]&&!times.includes(t))])];m.schedule=[...times].sort();m.frequency='每日 '+d.count+' 次';m.logs=Object.fromEntries(times.map(t=>[t,!!oldLogs[t]]));m.reminders=Object.fromEntries(times.map((t,i)=>[t,!!d['remind'+i]]));m.taken=m.schedule.every(t=>m.logs[t]);savePets();sheet.close();const top=scroll.scrollTop;render();scroll.scrollTop=top;toast('用药时间、次数和提醒已更新');});
/* Present former sheets as full in-app pages, retaining their existing forms and actions. */
const subpageStack=[];let subpageOpen=false;
const originalSheetClose=sheet.close.bind(sheet);
function dismissSubpages(){if(!subpageOpen)return;subpageOpen=false;subpageStack.length=0;sheet.classList.remove('as-page');sheet.removeAttribute('open');sheet.style.display='';document.querySelectorAll('.phone > header,.phone > #scroll,.phone > nav').forEach(el=>el.inert=false);}
function modal(name,html){if(subpageOpen){const inputs=[...sheet.querySelectorAll('input,textarea,select')].map(el=>({name:el.name,value:el.value,checked:el.checked}));subpageStack.push({title:$('#sheet-title').textContent,html:$('#sheet-body').innerHTML,inputs,top:sheet.scrollTop});}else{subpageStack.length=0;subpageOpen=true;}if(sheet.open&&!sheet.classList.contains('as-page'))originalSheetClose();sheet.classList.add('as-page');sheet.setAttribute('open','');sheet.setAttribute('role','region');sheet.setAttribute('aria-labelledby','sheet-title');sheet.style.display='block';document.querySelectorAll('.phone > header,.phone > #scroll,.phone > nav').forEach(el=>el.inert=true);sheet.querySelector('.sheet-handle').hidden=true;const close=$('#close');close.innerHTML=I('back');close.setAttribute('aria-label','返回上一页');$('#sheet-title').textContent=name;$('#sheet-body').innerHTML=html;sheet.scrollTop=0;close.focus({preventScroll:true});}
sheet.close=function(){dismissSubpages();};
function backSubpage(){if(subpageStack.length){const prev=subpageStack.pop();$('#sheet-title').textContent=prev.title;$('#sheet-body').innerHTML=prev.html;for(const value of prev.inputs){const el=[...sheet.querySelectorAll('input,textarea,select')].find(el=>el.name===value.name);if(el){el.value=value.value;el.checked=value.checked;}}sheet.scrollTop=prev.top;}else{dismissSubpages();}}
document.addEventListener('click',e=>{if(subpageOpen&&e.target.closest('#close')){e.preventDefault();e.stopImmediatePropagation();backSubpage();}},true);
document.addEventListener('keydown',e=>{if(subpageOpen&&e.key==='Escape'){e.preventDefault();backSubpage();}});

/* Deletion stays scoped to the selected pet and requires an explicit confirmation page. */
function recordKey(r){return r.recordId||[r.date,r.name,r.hospital].join('|');}
function recordDeleted(r){return (currentPet().deletedRecords||[]).includes(recordKey(r));}
function deleteButton(kind,id,label){return `<button class="delete-entry" data-delete-kind="${kind}" data-delete-id="${esc(id)}">${label}</button>`;}
const settingsBeforeDelete=medicationSettings;
medicationSettings=function(id){settingsBeforeDelete(id);(document.querySelector('#light-editor-body')||$('#sheet-body')).insertAdjacentHTML('beforeend',deleteButton('med',String(id),'删除此用药'));};
function openDeletableRecord(r){
 if(r.voiceDetails&&r.recordId){activeVoiceVisit=r.recordId;go('visit');return;}
 modal(r.name,`<div class="detail"><b>${esc(r.date)} · ${esc(r.type)}</b><p>${esc(r.hospital)}<br>${esc(r.doctor||'医生待补充')}</p>${tags(r.tags||[])}<p>${esc(r.result||'')}</p></div>${r.detail?`<p class="microcopy">${esc(r.detail)}</p>`:''}${deleteButton('record',recordKey(r),'删除就诊记录')}`);
}
const renderBeforeDeletion=render;
render=function(){renderBeforeDeletion();
 if(state.route==='visit'){
 const r=state.extraRecords.find(r=>r.recordId===activeVoiceVisit&&r.voiceDetails);
 if(!r&&(currentPet().deletedRecords||[]).includes('default-visit')){scroll.innerHTML='<div class="empty-pet-state"><h2>这条就诊记录已删除</h2><p>你可以在医疗档案中查看或添加其他记录。</p><button class="outline-btn" data-route="archive">查看医疗档案</button></div>';footer('');}
 else scroll.insertAdjacentHTML('beforeend',deleteButton('record',r?recordKey(r):'default-visit','删除就诊记录'));
 }
 if(state.route==='archive'){
 if(state.archiveTab==='诊断记录'){
 const records=[...state.extraRecords,...(currentPet().id==='doudou'?baseRecords.filter(r=>!recordDeleted(r)):[])].filter(r=>r.type==='就诊');
 scroll.querySelectorAll('.section-block,.empty-pet-state').forEach(el=>el.remove());
 const anchor=scroll.querySelector('.archive-tabs');
 anchor.insertAdjacentHTML('afterend',records.map(r=>`<button class="section-block full-width left" data-delete-record-open="${esc(recordKey(r))}"><h2>${esc(r.name)}</h2><p>${esc(r.date)} · ${esc(r.hospital)}</p><span class="text-link">查看就诊详情 →</span></button>`).join('')+((currentPet().id==='doudou'&&!(currentPet().deletedRecords||[]).includes('default-visit'))?'<button class="section-block full-width left" data-route="visit"><h2>急性胃肠炎</h2><p>2025.08.14 · 瑞鹏宠物医院</p><span class="text-link">查看就诊详情 →</span></button>':''));
 }
 if(state.archiveTab==='疫苗驱虫'&&recordDeleted(baseRecords[2]))scroll.querySelector('.section-block')?.remove();
 if(state.archiveTab==='检查报告'&&(currentPet().deletedRecords||[]).includes('default-visit'))scroll.querySelector('.section-block')?.remove();
 if(state.archiveTab==='时间轴'&&!scroll.querySelector('.timeline-item')){const timeline=scroll.querySelector('.timeline');if(timeline)timeline.innerHTML='<div class="empty-pet-state"><h2>暂无医疗记录</h2><p>添加就诊记录，持续保存健康信息。</p></div>';}
 }
};
window.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.timeline!==undefined||b.dataset.deleteRecordOpen){const records=[...state.extraRecords,...(currentPet().id==='doudou'?baseRecords.filter(r=>!recordDeleted(r)):[])];const r=b.dataset.deleteRecordOpen?records.find(r=>recordKey(r)===b.dataset.deleteRecordOpen):records[+b.dataset.timeline];if(r){e.preventDefault();e.stopImmediatePropagation();openDeletableRecord(r);}return;}
 if(b.dataset.deleteKind){e.preventDefault();e.stopImmediatePropagation();const kind=b.dataset.deleteKind,id=b.dataset.deleteId;const m=state.meds.find(m=>String(m.id)===id);modal(kind==='med'?'删除用药':'删除就诊记录',`<div class="detail"><b>${kind==='med'?esc(m?.name||'此用药'):'确认删除这条就诊记录？'}</b><p>${kind==='med'?'删除后，这项用药的服药任务、提醒和完成记录将一并移除。':'删除后将从当前宠物的医疗档案移除，已经生成的用药计划会保留。'}</p></div><p class="microcopy">此操作无法撤销，请确认后再删除。</p><button class="cta" data-confirm-delete="${kind}" data-delete-target="${esc(id)}">确认删除</button><button class="add-button" data-cancel-delete>暂不删除</button>`);return;}
 if(b.hasAttribute('data-cancel-delete')){e.preventDefault();e.stopImmediatePropagation();backSubpage();return;}
 if(b.dataset.confirmDelete){e.preventDefault();e.stopImmediatePropagation();const id=b.dataset.deleteTarget;if(b.dataset.confirmDelete==='med'){state.meds=state.meds.filter(m=>String(m.id)!==id);savePets();go('medication');toast('用药及对应提醒已删除');}else{currentPet().deletedRecords=[...new Set([...(currentPet().deletedRecords||[]),id])];state.extraRecords=state.extraRecords.filter(r=>recordKey(r)!==id&&(id!=='default-visit'||!r.visit));if(id==='default-visit')state.archived=false;activeVoiceVisit=null;savePets();state.archiveTab='时间轴';go('archive');toast('就诊记录已删除');}}
},true);
render();

function closeSpecialtyDropdown(){scroll.querySelector('#specialty-dropdown')?.remove();scroll.querySelector('[data-filter="专科筛选"]')?.setAttribute('aria-expanded','false');}
function toggleSpecialtyDropdown(trigger){
 if(scroll.querySelector('#specialty-dropdown')){closeSpecialtyDropdown();return;}
 trigger.setAttribute('aria-expanded','true');
 scroll.querySelector('.filter-bar').insertAdjacentHTML('afterend',`<section id="specialty-dropdown" class="specialty-dropdown" aria-label="选择专科"><div class="specialty-dropdown-heading">选择专科<button data-close-specialty aria-label="收起专科筛选">收起 ${I('chevron')}</button></div><div class="specialty-dropdown-options">${['全部','皮肤','猫科','内科','体检'].map(v=>`<button data-specialty="${v}" aria-pressed="${state.specialty===v}" class="${state.specialty===v?'selected':''}">${v}${state.specialty===v?I('check'):''}</button>`).join('')}</div></section>`);
}
document.addEventListener('click',e=>{if(e.target.closest('[data-close-specialty]')){closeSpecialtyDropdown();scroll.querySelector('[data-filter="专科筛选"]')?.focus({preventScroll:true});}else if(!e.target.closest('#specialty-dropdown,[data-filter="专科筛选"]'))closeSpecialtyDropdown();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&scroll.querySelector('#specialty-dropdown')){closeSpecialtyDropdown();scroll.querySelector('[data-filter="专科筛选"]')?.focus({preventScroll:true});}});
// Fit the entire handset proportionally, including browser/OS display scaling.
function fitHandsetPreview(){const scale=Math.min(1,(window.innerWidth-32)/393,(window.innerHeight-32)/852);document.documentElement.style.setProperty('--handset-scale',String(Math.max(.1,scale)));}
fitHandsetPreview();window.addEventListener('resize',fitHandsetPreview);
const renderBeforeHospitalDetails=renderHospitals;
renderHospitals=function(){renderBeforeHospitalDetails();scroll.querySelectorAll('.hospital-main').forEach((el,i)=>{const h=filteredHospitals()[i];el.setAttribute('role','button');el.tabIndex=0;el.dataset.hospitalDetail=h.id;el.setAttribute('aria-label','查看'+h.name+'详情');});};
function hospitalDetails(id){const h=hospitals.find(h=>h.id===id);if(!h)return;modal('医院详情',`<section class="visit-header">${hospitalPhoto(h)}<div><h2>${esc(h.name)}</h2><p>${esc(h.branch)} · ${esc(h.area)}</p><p>★ ${h.rating} · 距你 ${h.distance} km</p></div></section>${tags(h.tags)}<div class="detail"><b>接诊信息</b><p>营业时间：${esc(h.hours)}</p><p>参考费用：${esc(h.price)}</p></div><div class="detail"><b>医院特色</b><p>${esc(h.feature)}</p></div><div class="detail"><b>就诊准备</b><p>带好报告与处方，整理近期症状。</p></div><p class="microcopy">演示资料 · 接诊与费用以医院确认为准</p><div class="hospital-detail-actions"><button class="outline-btn" data-detail-toggle="${id}">${state.compare.includes(id)?'移出对比':'加入对比'}</button><button class="cta" data-detail-appointment="${id}">预约这家医院</button></div>`);}
document.addEventListener('click',e=>{const entry=e.target.closest('[data-hospital-detail]');if(entry){hospitalDetails(+entry.dataset.hospitalDetail);return;}const b=e.target.closest('button');if(!b)return;if(b.dataset.detailToggle){const id=+b.dataset.detailToggle;if(state.compare.includes(id))state.compare=state.compare.filter(x=>x!==id);else if(state.compare.length<2)state.compare.push(id);else{toast('最多选择两家医院进行对比');return;}b.textContent=state.compare.includes(id)?'移出对比':'加入对比';const top=scroll.scrollTop;render();scroll.scrollTop=top;}if(b.dataset.detailAppointment){const h=hospitals.find(h=>h.id===+b.dataset.detailAppointment);modal('预约就诊',`<form id="booking-form" class="entry-form"><div class="detail"><b>${esc(h.name)} · ${esc(h.branch)}</b><p>${esc(currentPet().name)}</p></div><label>意向日期<input name="date" type="date" required></label><label>意向时段<select name="slot"><option>上午 10:00</option><option>下午 14:00</option><option>晚上 19:00</option></select></label><p class="microcopy">演示预约，不占用真实医院号源，时段须由医院确认。</p><button class="cta" type="submit">确认演示预约</button></form>`);}});
document.addEventListener('keydown',e=>{const el=e.target.closest('[data-hospital-detail]');if(el&&(e.key==='Enter'||e.key===' ')){e.preventDefault();hospitalDetails(+el.dataset.hospitalDetail);}});

/* Shallow navigation and small, accessible motion. */
function syncCoreNavigation(){nav.style.display='flex';nav.inert=false;const section=subpageOpen?(/医院|预约|就医/.test($('#sheet-title').textContent)?'care':/用药/.test($('#sheet-title').textContent)?'medicine':null):null;const active=section||({home:'home',symptom:'care',hospitals:'care',compare:'care',visit:'archive',archive:'archive',medication:'medicine',profile:'pet',petdetail:'pet'})[state.route];nav.querySelectorAll('button').forEach(b=>{b.classList.toggle('active',b.dataset.nav===active);if(b.dataset.nav===active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
function enterMotion(el){if(!el||matchMedia('(prefers-reduced-motion: reduce)').matches||document.documentElement.classList.contains('reduce-motion'))return;el.animate([{opacity:.5,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:180,easing:'ease-out'});}
const renderWithCoreNav=render;render=function(){renderWithCoreNav();syncCoreNavigation();};
const modalWithCoreNav=modal;modal=function(name,html){modalWithCoreNav(name,html);syncCoreNavigation();enterMotion($('#sheet-body'));};
const goWithMotion=go;go=function(route,back=false){goWithMotion(route,back);enterMotion(scroll);};
const backWithCoreNav=backSubpage;backSubpage=function(){backWithCoreNav();syncCoreNavigation();};
window.addEventListener('click',e=>{const b=e.target.closest('nav [data-nav]');if(!b)return;if(typeof guardCoreEditExit==='function'&&guardCoreEditExit(e,b))return;e.preventDefault();e.stopImmediatePropagation();if(sheet.open)sheet.close();state.history=[];if(b.dataset.nav==='care'){careChoice();return;}go(({home:'home',archive:'archive',medicine:'carehub',pet:'profile'})[b.dataset.nav],true);},true);
function showWelcome(){if($('#welcome-screen'))return;const screen=document.createElement('section');screen.id='welcome-screen';screen.setAttribute('aria-label','欢迎使用 PawCare');screen.innerHTML=`<div class="welcome-visual" role="img" aria-label="女主人与猫依偎着看窗外风景"></div><div class="welcome-panel"><div class="welcome-brand"><div class="welcome-wordmark">${I('paw')}<h1>PawCare</h1></div><p>陪你记录每一次照护</p></div><div class="welcome-actions"><button class="cta" data-demo-enter><span>进入体验</span><span class="welcome-enter-arrow" aria-hidden="true">${I('arrow')}</span></button><small>免注册体验 · 演示数据</small></div></div>`;$('.phone').append(screen);for(const el of $('.phone').children)if(el!==screen&& !el.classList.contains('status')&&!el.classList.contains('home-indicator'))el.inert=true;}
document.addEventListener('click',e=>{if(e.target.closest('[data-demo-enter]')){try{sessionStorage.setItem('pawcare-demo-entered','1');}catch{}$('#welcome-screen')?.remove();for(const el of $('.phone').children)el.inert=false;go('home',true);}if(e.target.closest('[data-welcome-again]'))showWelcome();});
const profileWithWelcome=renderProfile;renderProfile=function(){profileWithWelcome();scroll.insertAdjacentHTML('beforeend','<button class="account-return" data-welcome-again>返回启动页</button>');};
render();let demoEntered=false;try{demoEntered=sessionStorage.getItem('pawcare-demo-entered')==='1';}catch{}if(!demoEntered)showWelcome();
// One-time cleanup requested for Kele's visit records; future additions remain available.
if(!petStore.keleVisitsClearedV1){
 const data=petStore.data?.kele;
 if(data){data.extraRecords=(data.extraRecords||[]).filter(r=>r.type!=='就诊'&&!r.voiceDetails&&!r.visit);data.archived=false;}
 if(petStore.active==='kele'){state.extraRecords=(state.extraRecords||[]).filter(r=>r.type!=='就诊'&&!r.voiceDetails&&!r.visit);state.archived=false;activeVoiceVisit=null;}
 petStore.keleVisitsClearedV1=true;savePets();render();
}
/* Compact illustrative thumbnails for diagnosis records. */
const renderBeforeDiagnosisThumbnails=render;
render=function(){renderBeforeDiagnosisThumbnails();if(state.route==='archive'&&state.archiveTab==='诊断记录'){
 scroll.querySelectorAll('[data-delete-record-open], [data-saved-voice], button.section-block[data-route="visit"]').forEach((card,i)=>{
 if(card.querySelector('.diagnosis-thumbnail'))return;
 card.classList.add('diagnosis-record-card');
 const isSkin=card.textContent.includes('皮肤');
 const visual=isSkin?avatar():crop(4,.052,.689,.218,.065,'','诊疗报告示意缩略图');
 card.insertAdjacentHTML('afterbegin',`<span class="diagnosis-thumbnail" aria-label="${isSkin?'宠物照片':'报告示意图'}">${visual}</span>`);
 });
}};
/* Data-led visual variety, using only existing pet and medication information. */
function careRing(done,total,label){const n=Math.max(0,Math.min(done,total)),pct=total?n/total:0;return `<div class="care-ring" role="img" aria-label="${esc(label)}：${n}/${total}"><svg viewBox="0 0 64 64" aria-hidden="true"><circle class="ring-track" cx="32" cy="32" r="26"/><circle class="ring-value" cx="32" cy="32" r="26" stroke-dasharray="${pct*163.36} 163.36"/></svg><strong>${n}<small>/${total}</small></strong></div>`;}
function companionSketch(){return `<div class="companion-sketch" aria-hidden="true"><svg viewBox="0 0 120 84"><ellipse cx="60" cy="73" rx="43" ry="6" fill="#F6EDF0" stroke="none"/><path d="M33 56V26l16 9q12-5 24 0l15-9v30q0 17-27 17T33 56Z"/><path d="m41 33 7 7m32-7-7 7M47 51q4 4 8 0m13 0q4 4 8 0m-18 5 4 3 4-3m-4 3v5m-17-5-13-2m13 7-12 2m44-7 13-2m-13 7 12 2"/><path class="sketch-accent" d="M98 17c-6-8-15 1 0 11 15-10 6-19 0-11Z"/></svg></div>`;}
function enrichCareVisuals(){
 if(state.route==='home'){
 const heading=scroll.querySelector('.reminders .section-heading');
 const total=state.meds.reduce((n,m)=>n+timesFor(m).length,0),done=state.meds.reduce((n,m)=>n+timesFor(m).filter(t=>logFor(m)[t]).length,0);
 if(heading&&total)heading.insertAdjacentHTML('afterend',`<div class="today-progress">${careRing(done,total,'今日用药已完成')}<div><b>${total-done?`还有 ${total-done} 次用药`:'今日用药已完成'}</b><span>今日用药</span></div><span class="progress-status">${done===total?'已完成':'进行中'}</span></div>`);
 }
 if(state.route==='medication'&&state.medTab==='当前用药'){
 scroll.querySelectorAll('.med-card').forEach((card,i)=>{const m=state.meds[i];if(!m)return;const copy=card.querySelector('.progress-copy');if(copy){copy.outerHTML=`<div class="course-progress">${careRing(Math.min(+m.day,+m.days),+m.days,'疗程进度')}<div><b>疗程进度</b><p>已用 ${m.day} 天 · 共 ${m.days} 天</p></div></div>`;card.querySelector('.progress-track')?.remove();}});
 const review=scroll.querySelector('.review-card');if(review&&/^\d{4}-\d{2}-\d{2}$/.test(state.review||'')){const parts=state.review.split('-');review.firstElementChild?.remove();review.insertAdjacentHTML('afterbegin',`<div class="review-date" aria-label="${esc(state.review)}"><span>${Number(parts[1])}月</span><b>${parts[2]}</b></div>`);}
 }
 if(state.route==='archive'&&state.archiveTab==='时间轴')scroll.querySelectorAll('.timeline-date>span').forEach(el=>{const icon=el.textContent==='疫苗'?'shield':el.textContent==='体检'?'clipboard':'stethoscope';el.insertAdjacentHTML('afterbegin',I(icon));});
 scroll.querySelectorAll('.empty-pet-state').forEach(el=>{if(!el.querySelector('.companion-sketch')){el.querySelector(':scope>svg,:scope>span[data-icon]')?.remove();el.insertAdjacentHTML('afterbegin',companionSketch());}});
}
const renderBeforeCareVisuals=render;render=function(){renderBeforeCareVisuals();enrichCareVisuals();};
const modalBeforeCareVisuals=modal;modal=function(name,html){modalBeforeCareVisuals(name,html);const success=sheet.querySelector('.booking-success');if(success&&!success.querySelector('.companion-sketch')){success.querySelector(':scope>svg')?.remove();success.insertAdjacentHTML('afterbegin',companionSketch());}};
render();
/* Symptom entry identity card, reusing each pet's saved profile. */
const renderBeforeSymptomPetCard=render;
render=function(){renderBeforeSymptomPetCard();if(state.route!=='symptom')return;const p=currentPet(),slot=scroll.querySelector('.pet-mini');if(!slot)return;const status=state.symptoms.length?'症状待评估':'健康待记录';slot.outerHTML=`<section class="symptom-pet-card"><div class="symptom-pet-copy"><button class="symptom-pet-switch" data-symptom-pet-picker aria-label="当前宠物${esc(p.name)}，点击切换"><b>${esc(p.name)}</b>${I('chevron')}</button><p>${esc(p.breed)} · ${petAge(p)} · ${esc(p.sex)}</p><span class="symptom-pet-status">${I('heart')}${status}</span></div>${avatar(p)}</section>`;};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-symptom-pet-picker'))modal('选择本次就医的宠物',`<div class="symptom-pet-options">${petStore.pets.map(p=>`<button data-symptom-pet="${esc(p.id)}" aria-pressed="${p.id===currentPet().id}">${avatar(p)}<div><b>${esc(p.name)}</b><p>${esc(p.breed)} · ${petAge(p)}</p></div>${I(p.id===currentPet().id?'check':'chevron')}</button>`).join('')}</div>`);if(b.dataset.symptomPet){sheet.close();switchPet(b.dataset.symptomPet);savePets();scroll.scrollTop=0;}});
/* A text-free companion photograph before hospital filters. */
const renderHospitalsBeforeCompanionPhoto=renderHospitals;
renderHospitals=function(){renderHospitalsBeforeCompanionPhoto();const filter=scroll.querySelector('.filter-bar');if(filter&&!scroll.querySelector('.hospital-companion-card'))filter.insertAdjacentHTML('beforebegin','<div class="hospital-companion-card"><img src="assets/pet-ragdoll-banner.png" alt="柔和自然光下的布偶猫" width="2172" height="724" decoding="async"></div>');};
/* Gentle context beneath the two care choices, without adding an action. */
const careChoiceBeforeCompanion=careChoice;
careChoice=function(){careChoiceBeforeCompanion();const options=sheet.querySelector('.care-choice-options');if(!options)return;const labels=['适合症状不明确','适合疫苗 / 体检 / 复诊'];options.querySelectorAll(':scope>button').forEach((card,i)=>{const copy=card.querySelector('div');if(copy)copy.insertAdjacentHTML('beforeend',`<span class="care-choice-label">${labels[i]}</span>`);});options.insertAdjacentHTML('afterend',`<section class="care-companion-strip"><img src="assets/welcome-companion.png" alt="主人与猫安静依偎" decoding="async"><p>确认需求，<br>一起整理下一步。</p></section><ol class="care-flow-hint" aria-label="就医流程"><li><span>1</span>选择需求</li><li aria-hidden="true">→</li><li><span>2</span>整理信息</li><li aria-hidden="true">→</li><li><span>3</span>推荐医院</li></ol>`);};
/* Photo-led pet identity and a focused voice-entry card on symptom input. */
const renderBeforeSymptomVoiceCard=render;
render=function(){renderBeforeSymptomVoiceCard();if(state.route!=='symptom')return;const p=currentPet();const card=scroll.querySelector('.symptom-pet-card');if(card)card.classList.add('photo-led');const voice=scroll.querySelector('.voice-entry[data-action="voice"]');if(!voice)return;const filled=!!(state.symptoms.length||state.duration||state.appetite||state.energy);const labels=filled?[...new Set([...state.symptoms,state.duration,state.appetite&&'食欲'+state.appetite,state.energy&&'精神'+state.energy].filter(Boolean))].slice(0,4):['呕吐','1–3天','食欲下降','精神稍差'];voice.outerHTML=`<section class="symptom-voice-card"><h2>用语音描述${esc(p.name)}的症状</h2><p class="symptom-voice-caption">说说最近的变化，我来帮你整理</p><div class="symptom-voice-input"><div class="voice-example"><span>语音示例</span><p>这两天${esc(p.name)}一直吐，吃得少，精神也不太好。</p></div><button class="voice-mic-action" data-action="voice" aria-label="语音描述${esc(p.name)}的症状">${I('mic')}<span>语音描述</span></button></div><div class="voice-summary-tags"><span class="voice-summary-label">${filled?'当前已填信息':'示例整理结果'}</span><div>${labels.map(label=>`<span>${esc(label)}</span>`).join('')}</div></div></section>`;};
/* Task-first care choice, replacing the previous decorative composition. */
careChoice=function(){const p=currentPet();modal('这次想为宠物做什么？',`<div class="care-task-page"><div class="care-identity">${avatar(p)}<span><b>${esc(p.name)}</b> · ${esc(p.breed)} · ${petAge(p)}</span></div><div class="care-task-choices"><button data-care-path="symptoms" class="care-task-card"><span class="care-task-icon">${I('stethoscope')}</span><div><span class="care-task-tag">症状评估</span><h2>发现异常，还不清楚原因</h2><p>症状不明确时，先帮你整理情况</p></div>${I('chevron')}</button><button data-care-path="purpose" class="care-task-card"><span class="care-task-icon">${I('calendar')}</span><div><span class="care-task-tag">直接预约</span><h2>已经知道要去做什么</h2><p>疫苗、体检、驱虫、复诊</p></div>${I('chevron')}</button></div><button class="care-task-help" data-care-path="symptoms"><span>不确定怎么选？先记录症状，<br>我们帮你判断下一步</span>${I('arrow')}</button></div>`);syncCoreNavigation();};
const syncNavBeforeCareTask=syncCoreNavigation;
syncCoreNavigation=function(){syncNavBeforeCareTask();if(subpageOpen&&sheet.querySelector('.care-task-page'))nav.querySelectorAll('button').forEach(b=>{const active=b.dataset.nav==='care';b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});};
/* Guided two-choice care entry. */
careChoice=function(){modal('这次想为宠物做什么？',`<div class="care-task-page"><p class="care-task-intro">告诉我们你的需求，我们会为你推荐合适的医院</p><ol class="care-entry-steps" aria-label="就医流程"><li aria-current="step"><span>1</span>选择需求</li><li><span>2</span>整理信息</li><li><span>3</span>推荐医院</li></ol><div class="care-task-choices"><button data-care-path="symptoms" class="care-task-card"><span class="care-task-icon">${I('stethoscope')}</span><div><h2>发现异常，还不清楚原因</h2><p>先整理症状，再推荐合适医院</p><div class="care-task-tags"><span>适合症状不明确</span><span>快速匹配</span><span>专业建议</span></div></div>${I('chevron')}</button><button data-care-path="purpose" class="care-task-card"><span class="care-task-icon">${I('calendar')}</span><div><h2>已经知道要去做什么</h2><p>体检、疫苗、驱虫、复诊</p><div class="care-task-tags"><span>适合按需就医</span><span>选择更高效</span><span>节省准备时间</span></div></div>${I('chevron')}</button></div></div>`);syncCoreNavigation();};
/* Animate only the selected control after a render, never the bottom navigation. */
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.closest('nav,.filter-bar,.archive-tabs,.medication-segments')||matchMedia('(prefers-reduced-motion: reduce)').matches||document.documentElement.classList.contains('reduce-motion'))return;const attrs=['data-choice','data-filter','data-archive-tab','data-med-tab','data-specialty','data-compare'];const attr=attrs.find(a=>b.hasAttribute(a));if(!attr)return;const value=b.getAttribute(attr),detail=b.getAttribute('data-value');requestAnimationFrame(()=>{const el=[...document.querySelectorAll('button')].find(x=>x.getAttribute(attr)===value&&(!detail||x.getAttribute('data-value')===detail));if(el&&(el.classList.contains('selected')||el.classList.contains('checked')||el.getAttribute('aria-pressed')==='true'))el.animate([{transform:'scale(.98)'},{transform:'scale(1)'}],{duration:200,easing:'ease-out'});});});
/* Hospital recommendations share the photo-led pet identity card. */
const renderHospitalsBeforePetIdentity=renderHospitals;
renderHospitals=function(){renderHospitalsBeforePetIdentity();const banner=scroll.querySelector('.hospital-companion-card');if(!banner)return;const p=currentPet();banner.outerHTML=`<section class="symptom-pet-card photo-led hospital-pet-identity"><div class="symptom-pet-copy"><button class="symptom-pet-switch" data-symptom-pet-picker aria-label="当前宠物${esc(p.name)}，点击切换"><b>${esc(p.name)}</b>${I('chevron')}</button><p>${esc(p.breed)} · ${petAge(p)} · ${esc(p.sex)}</p><span class="symptom-pet-status">${I('heart')}${state.symptoms.length?'症状待评估':'健康待记录'}</span></div>${avatar(p)}</section>`;};
/* Hospital filters use a sliding segmented selection surface. */
let hospitalSegmentIndex=0,hospitalSegmentFrom=null;
function syncHospitalSegment(){const bar=scroll.querySelector('.filter-bar');if(state.route!=='hospitals'||!bar)return;bar.classList.add('hospital-segments');bar.querySelector('.hospital-segment-indicator')?.remove();const buttons=[...bar.querySelectorAll('button')];hospitalSegmentIndex=Math.max(0,Math.min(3,hospitalSegmentIndex));buttons.forEach((b,i)=>{b.classList.toggle('selected',i===hospitalSegmentIndex);b.setAttribute('aria-pressed',String(i===hospitalSegmentIndex));});const marker=document.createElement('span');marker.className='hospital-segment-indicator';marker.setAttribute('aria-hidden','true');bar.prepend(marker);const width=(bar.clientWidth-8)/4;marker.style.width=width+'px';marker.style.transform=`translateX(${hospitalSegmentIndex*width}px)`;if(hospitalSegmentFrom!==null&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&!document.documentElement.classList.contains('reduce-motion'))marker.animate([{transform:`translateX(${hospitalSegmentFrom*width}px)`},{transform:`translateX(${hospitalSegmentIndex*width}px)`}],{duration:200,easing:'ease-in-out'});hospitalSegmentFrom=null;}
window.addEventListener('click',e=>{const b=e.target.closest('.filter-bar button[data-filter]');if(!b)return;hospitalSegmentFrom=hospitalSegmentIndex;hospitalSegmentIndex=[...b.parentElement.querySelectorAll('button')].indexOf(b);if(b.dataset.filter==='专科筛选')requestAnimationFrame(syncHospitalSegment);},true);
const renderBeforeHospitalSegments=render;render=function(){renderBeforeHospitalSegments();if(state.route==='hospitals')syncHospitalSegment();};
/* Medical archive shares the clean sliding segmented selector. */
let archiveSegmentFrom=null;
function syncArchiveSegment(){if(state.route!=='archive')return;const bar=scroll.querySelector('.archive-tabs');if(!bar)return;bar.classList.add('archive-segments');bar.querySelector('.archive-segment-indicator')?.remove();const buttons=[...bar.querySelectorAll('button')],index=Math.max(0,buttons.findIndex(b=>b.dataset.archiveTab===state.archiveTab));buttons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));const marker=document.createElement('span');marker.className='archive-segment-indicator';marker.setAttribute('aria-hidden','true');bar.prepend(marker);const width=(bar.clientWidth-8)/4;marker.style.width=width+'px';marker.style.transform=`translateX(${index*width}px)`;if(archiveSegmentFrom!==null&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&!document.documentElement.classList.contains('reduce-motion'))marker.animate([{transform:`translateX(${archiveSegmentFrom*width}px)`},{transform:`translateX(${index*width}px)`}],{duration:200,easing:'ease-in-out'});archiveSegmentFrom=null;}
window.addEventListener('click',e=>{const b=e.target.closest('[data-archive-tab]');if(b)archiveSegmentFrom=[...b.parentElement.querySelectorAll('button')].findIndex(x=>x.dataset.archiveTab===state.archiveTab);},true);
const renderBeforeArchiveSegments=render;render=function(){renderBeforeArchiveSegments();syncArchiveSegment();};
/* Medication tabs share the same sliding segmented treatment. */
let medicationSegmentFrom=null;
function syncMedicationSegment(){if(state.route!=='medication')return;const bar=scroll.querySelector('.tabs');if(!bar)return;bar.classList.add('medication-segments');bar.querySelector('.medication-segment-indicator')?.remove();const buttons=[...bar.querySelectorAll('button')],index=Math.max(0,buttons.findIndex(b=>b.dataset.medTab===state.medTab));buttons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));const marker=document.createElement('span');marker.className='medication-segment-indicator';marker.setAttribute('aria-hidden','true');bar.prepend(marker);const width=(bar.clientWidth-8)/buttons.length;marker.style.width=width+'px';marker.style.transform=`translateX(${index*width}px)`;if(medicationSegmentFrom!==null&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&!document.documentElement.classList.contains('reduce-motion'))marker.animate([{transform:`translateX(${medicationSegmentFrom*width}px)`},{transform:`translateX(${index*width}px)`}],{duration:200,easing:'ease-in-out'});medicationSegmentFrom=null;}
window.addEventListener('click',e=>{const b=e.target.closest('[data-med-tab]');if(b)medicationSegmentFrom=[...b.parentElement.querySelectorAll('button')].findIndex(x=>x.dataset.medTab===state.medTab);},true);
const renderBeforeMedicationSegments=render;render=function(){renderBeforeMedicationSegments();syncMedicationSegment();};
/* Photo-led, centered pet carousel in My Pets. */
const renderBeforeProfilePhotoCards=render;
render=function(){renderBeforeProfilePhotoCards();if(state.route!=='profile')return;const index=petStore.pets.findIndex(p=>p.id===currentPet().id);scroll.querySelectorAll('.pet-slide').forEach(card=>{card.classList.add('pet-photo-slide');const p=petStore.pets.find(p=>p.id===card.dataset.petId);if(!p)return;card.querySelector('.select-pet')?.remove();const main=card.querySelector('.pet-card-main');const info=main?.querySelector('div:not(.avatar)');if(info&&!info.querySelector('.pet-photo-status'))info.insertAdjacentHTML('beforeend',`<span class="pet-photo-status">${p.id===currentPet().id?'当前照护':'点击查看档案'}</span>`);});const hint=scroll.querySelector('.pet-switch-hint');if(hint)hint.outerHTML=`<div class="pet-carousel-controls"><button aria-label="上一只宠物" ${index>0?`data-select-pet="${petStore.pets[index-1].id}"`:'disabled'}>${I('back')}</button><span>${petStore.pets.length>1?'左右滑动切换宠物':'我的宠物'} <b>${index+1} / ${petStore.pets.length}</b></span><button aria-label="下一只宠物" ${index<petStore.pets.length-1?`data-select-pet="${petStore.pets[index+1].id}"`:'disabled'}>${I('chevron')}</button></div>`;};
/* Compact voice input: waveform, one action, and structured results. */
const renderBeforeCompactVoice=render;
render=function(){renderBeforeCompactVoice();if(state.route!=='symptom')return;const card=scroll.querySelector('.symptom-voice-card');if(!card)return;const labels=[...new Set([...state.symptoms,state.duration,state.appetite&&'食欲'+state.appetite,state.energy&&'精神'+state.energy].filter(Boolean))].slice(0,4);card.classList.add('compact-voice');card.innerHTML=`<div class="compact-voice-copy"><h2>语音描述症状</h2><p class="symptom-voice-caption">说说最近的变化，我来帮你整理</p><div class="voice-wave" aria-hidden="true">${[5,10,16,8,20,12,7,15,10,5,11,6].map((h,i)=>`<i style="--wave-height:${h}px;--wave-delay:${i*8}ms"></i>`).join('')}</div></div><button class="voice-mic-action" data-action="voice" aria-label="体验语音描述症状">${I('mic')}</button><div class="voice-summary-tags"><span class="voice-summary-label">${labels.length?'已识别 / 已填写':'待识别'}</span><div>${labels.map(label=>`<span>${esc(label)}</span>`).join('')}</div></div>`;};
window.addEventListener('click',e=>{const b=e.target.closest('.compact-voice:not(.visit-voice-card) .voice-mic-action');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.disabled)return;b.disabled=true;const card=b.closest('.compact-voice');card.classList.add('voice-activating');setTimeout(()=>{b.disabled=false;card.classList.remove('voice-activating');if(state.route==='symptom'&&!sheet.open)voice();},200);},true);
/* Visit details use pet-first identity, a hospital selector and compact voice input. */
function visitHospitalRecord(){return state.extraRecords.find(r=>r.voiceDetails&&r.recordId===activeVoiceVisit);}
function selectedVisitHospital(){return visitHospitalRecord()?.hospital||currentPet().visitHospital||'瑞鹏宠物医院 · 万象城分院';}
const renderBeforeVisitRefresh=render;
render=function(){renderBeforeVisitRefresh();if(state.route!=='visit')return;const header=scroll.querySelector('.visit-header');if(!header)return;const p=currentPet();const date=visitHospitalRecord()?.date||'2025.08.14';header.remove();const mini=scroll.querySelector('.pet-mini');if(mini)mini.outerHTML=`<section class="symptom-pet-card photo-led"><div class="symptom-pet-copy"><button class="symptom-pet-switch" data-route="petdetail"><b>${esc(p.name)}</b>${I('chevron')}</button><p>${esc(p.breed)} · ${petAge(p)} · ${esc(p.sex)}</p><span class="symptom-pet-status">${I('record')}就诊记录</span></div>${avatar(p)}</section><button class="visit-hospital-select" data-visit-hospital-picker><span>${I('stethoscope')}</span><div><small>选择医院</small><b>${esc(selectedVisitHospital())}</b><p>${esc(date)} · ${esc(visitHospitalRecord()?.doctor||(p.visitHospital?'医生待补充':'李医生 · 猫科'))}</p></div>${I('chevron')}</button>`;
const entry=scroll.querySelector('[data-visit-voice]');if(entry)entry.outerHTML=`<section class="symptom-voice-card compact-voice visit-voice-card"><div class="compact-voice-copy"><h2>语音整理诊断记录</h2><p class="symptom-voice-caption">说说医生的医嘱，我来帮你整理</p><div class="voice-wave" aria-hidden="true">${[5,10,16,8,20,12,7,15,10,5,11,6].map(h=>`<i style="--wave-height:${h}px"></i>`).join('')}</div></div><button class="voice-mic-action" data-visit-voice aria-label="体验语音整理诊断记录">${I('mic')}</button><div class="voice-summary-tags"><span class="voice-summary-label">${visitHospitalRecord()?'已确认':'整理内容'}</span><div><span>就诊原因</span><span>医生诊断</span><span>治疗方案</span></div></div></section>`;
};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-visit-hospital-picker'))modal('选择就诊医院',`<div class="visit-hospital-options">${hospitals.map(h=>`<button data-visit-hospital-id="${h.id}" aria-pressed="${selectedVisitHospital().includes(h.name)}">${hospitalPhoto(h)}<div><b>${esc(h.name)}</b><p>${esc(h.branch)} · ${esc(h.area)}</p></div>${I(selectedVisitHospital().includes(h.name)?'check':'chevron')}</button>`).join('')}</div>`);if(b.dataset.visitHospitalId){const h=hospitals.find(h=>h.id===+b.dataset.visitHospitalId);if(!h)return;const name=h.name+' · '+h.branch,r=visitHospitalRecord();if(r){r.hospital=name;r.voiceDetails.hospital=name;r.doctor='医生待补充';}else currentPet().visitHospital=name;savePets();sheet.close();render();}});
const draftBeforeHospitalSelection=visitVoiceDraft;visitVoiceDraft=function(){draftBeforeHospitalSelection();const input=sheet.querySelector('[name="hospital"]');if(input)input.value=selectedVisitHospital();};

